### ISSUE TITLE
allow use of 'with' for roles or 'implements' for interefaces inside generics

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#10]
IDEBUG-169
 in the following case

```
interface IBeverage {
    public drink();
}

role Alcohol {
    public getWasted() {}
}

class Beer with Alcohol implements IBeverage {
    @Override 
    public drink() {
        this.getWasted();
    }
}

class Coors extends Beer {}
```

In order to create a generic restricting to just the implementers of the interface or classes used with a role you have to use 'extends' in your generic definition.

It would be useful to use the same restriction on keywords in the generic definition as we use in our class definitions. So:

```
//Proposal
var Array<? implements IBeverage> drinks = [new Beer()];
var Array<? with Alcohol> boozyDrinks = [new Beer()];
var Array<? extends Beer> beers = [new Coors()];

/*
 * Currently this would have to be done with 'extends' regardless of if role or interface a la
 * var Array<? extends IBeverage> drinks = [new Beer()];
 * var Array<? extends Alcohol> boozyDrinks = [new Beer()];
 * var Array<? extends Beer> beers = [new Coors()];
 */
```

This should be fixed already, review tests and close bug.

**Comment by mor-n4** [comment]
this is working

(but note that for upper bounds of wildcards you always use keyword "extends", even for interfaces:

```
var arr: Array<? extends IBeverage>;
```

roles and "with" are obsolete anyway, replaced by interfaces with default methods)

--> closing this now

**Comment by mor-n4** [comment]
if the ticket was about using keyword "implements" also for upper bounds of wildcards in case of interfaces, then the reason for closing is: good idea, would be more consistent, but (1) we should stick to Java and (2) "extends" is used in all cases, here, because the distinction between extension and implementation does not matter, here.
