### ISSUE TITLE
New Class Wizard, visibility-buttons disable @Internal but never re-enable it.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#102]
IDEBUG-825
 Opening the new class wizard, entering name and module-specifier, giving it visibility of public@internal.

Now click through the radio-buttons public / protected / private.

When hitting private the @internal checkbox gets unchecked & disabled, which is correct.

BUT: Clicking back to public or protected never reenables the @internal checkbox.

**Comment by lbeurerkellner** [comment]
This was fixed by another task. In the current build the @Internal checkbox gets reenabled correctly.
