### ISSUE TITLE
Organize imports moves import block above file comment (above copyright notice for example)

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#103]
IDEBUG-826
 Before: 

``` javascript
/**
 * Copyright (c) 2016 NumberFour AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   NumberFour AG - Initial API and implementation
 */
import {Assert} from "n4/mangel/assert/Assert"
import {AssertionError} from "n4/mangel/assert/AssertionError"
import {ErrorPrimitiveType} from "n4/mangel/assert/ErrorPrimitiveType"
import {DataList} from "n4/model/collections/DataList"
```

after:

``` javascript
import { Assert } from "n4/mangel/assert/Assert"
import { AssertionError } from "n4/mangel/assert/AssertionError"
import { ErrorPrimitiveType } from "n4/mangel/assert/ErrorPrimitiveType"
import { DataList } from "n4/model/collections/DataList"
/**
 * Copyright (c) 2016 NumberFour AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   NumberFour AG - Initial API and implementation
 */
```

**Comment by torstenkraemer** [comment]
The example here is a little bit out of shape. IMHO jsdoc-style comments - starting with "/*_" - are supposed to comment semantic things in the file & attached. Preambles like this copy right header here should be put in plain multiline comments - starting with "/_". 

Following that agreement we could formulate a simple 3-step rule:
1. import statements go after script-annotations (`@@xyz`), if any
2. find the first (non-'directive prologue') statement (e.g. `"use strict";` doesn't count but `class x ....` does.) 
3. If there is any jsdoc-style comment between 1. and 2. it goes directly above the first one, else it goes directly above the statement from 2.  

Note: The case that in 2. no statement can be found AND something needs to be imported can not happen at the same time.

**Comment by torstenkraemer** [comment]
Update to point 3 of last comment:
If there is no comment at all before the first statement, the imports should go to the top of the file or just after 1.)
