### ISSUE TITLE
Clean-up: change system loader flag for commonjs from cmd-line-option to property in execution data

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#105]
IDEBUG-828
 When running n4js code, we allow to define the module loader to be used (SystemJS or CommonJS). This is required for tests.

Currently, we pass this info as a command line argument "cjs" (SystemJS is the default). See eu.numberfour.n4js.runner.nodejs.NodeEngineCommandBuilder.createCmds(NodeRunOptions).

In this task, remove this command line argument and instead provide this information to the bootstrap code as part of the execution data.

Note that bootstrap code has to be adjusted (discuss with Daniel).

Note that this might make the field "systemLoader" in class RunConfiguration obsolete (including related getters, setters). If so, remove this field.

If the "systemLoader" is considered to be obsolete, clean up the tester code as well. And remove the UI contribution in the configuration tabs.

**Comment by mor-n4** [comment]
changing this from "bug" to "refactoring"
(it would be nice to have as a clean-up, but the current solution does not cause any problems and so this is not a bug)

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/598
