### ISSUE TITLE
Add warning for unused variables

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#11]
IDEBUG-218

```
class A {
    void foo() {
        // XPECT FIXME warnings --> "unused variable"
        var number n;
    }
}

```

**Comment by arrowplum** [comment]
Is it possible to raise the prio here? Refactorings leave variables behind, it would be nice to have a tool to help clean them up.

**Comment by JensN4** [comment]
set prio to normal... this is a perfect task for newcomers
