### ISSUE TITLE
Run npm uninstall from npm manager to avoid a corrupted package.json state

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#112]
IDEBUG-838
 Run `npm uninstall` from npm manager to avoid a corrupted package.json state
This uninstall should be performed when `npm install`was successful, but the n4js project structure adaption or type definition file support fails (which would lead to a messed up project). This means we basically roll-back the installation to not have undefined state there. In that case, the user has to be notified about the problem.

**Comment by JensN4** [comment]
In general we should provide a method to completely clean the library cache and re-install them all. This is required when we update the N4IDE in some cases.

**Comment by kduske-n4** [comment]
This might also be relevant for the N4JS tasks example wizard, which installs the required dependencies automatically as of #259. If the installation fails, we should instruct the user to reset their library cache and try again.

**Comment by yoosiba** [comment]
removing npms is now supported in the library manager, see cd8239bcdb8e60fd8934849a94d7abc9e1426eb7
