### ISSUE TITLE
consolidate handling processes on different OSes

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#114]
IDEBUG-840
 On windows and Unix (and Mac) we spawn processes that call native external tools, i.e. shell (that triggers node, or npm via node).

We have three different places where we do this (NpmmainModuleResolver, NpmConnector, BinariesValidator).

Currently each of those contains each own process creation, which in each case has to handle all platforms.

There is some code duplication between those.

Refactor process creation and handling.

**Comment by yoosiba** [comment]
Resolved with 1c4f0932dd5fdc0a4293f7149ed346827bf69d7e and minor adjustment 30816136e42fa3c599471067bb429bc72eb406ad. Eager version logging is tracked by #144.
