### ISSUE TITLE
Remove hard-coded eu.numberfour vendor in the project wizard

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#121]
IDEBUG-860

```
Sources {
        test { 
            "src"
    }
}
```

Additionally:
- Should we really use a VendorId {{eu.numberfour}}?
- We still append the OSGi {{-SNAPSHOT}} suffix, which people need to manually remove for npm export.

**Comment by lbeurerkellner** [comment]
This behaviour was implemented with IDE-2098: "As a developer I need a N4JS test project wizard"

**Comment by lbeurerkellner** [comment]
What remains to be fixed is that
- The vendor id should be empty
- The version snapshot suffix should be removed

**Comment by lbeurerkellner** [comment]
A manifest file doesn't allow empty vendor ids.
This means a preferences option and/or a wizard option should be provided to configure the vendor id.

**Comment by lbeurerkellner** [comment]
Renamed the issue to reflect the status of the issue.
