### ISSUE TITLE
Add fail-fast check for leaking UnknownTypeRefs

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#122]
IDEBUG-862
 UnknownTypeRefs should only appear in case of a validation error. To make sure we do not "leak" UnknownTypeRefs into a error-free resource, add the following validation:

"If a resource contains an UnknownTypeRef anywhere AND this resource does not have a validation error (i.e. issue of priority error), then show an error."

(note that this validation, of course, has to be executed after all other validations have taken place).

**Comment by JensN4** [comment]
typo, was not closed
