### ISSUE TITLE
Missing API/Impl stub of a missing getter shadows existing setter (if setter defined in a super class)

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#123]
IDEBUG-863
 If we have a getter/setter pair in the API and the Impl only provides a setter in a super class, then the API/Impl stub for the missing getter will shadow the setter in the super class.

See the following test case:

```
eu.numberfour.n4js.hlc.IncompleteApiImplementationTest#testfield_vs_getset_D()
```

This test is currently on ignore. Re-activate it, and the problem will show.

**Comment by mor-n4** [comment]
see IDE-2228

**Comment by torstenkraemer** [comment]
Fixed during works on IDE-2340, cf. 45ae81bb3de3aba95aa3b480d40a39429c815f26
