### ISSUE TITLE
Broken NewClassWizard on Windows

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#128]
IDEBUG-872
 `Module specifier` text field is black on windows.
See screenshot
![a](https://cloud.githubusercontent.com/assets/944287/14452719/d46f1420-0090-11e6-9176-dd1382dd2290.PNG)
![b](https://cloud.githubusercontent.com/assets/944287/14452720/d47017b2-0090-11e6-8f98-3207645b6f4c.PNG)

**Comment by lbeurerkellner** [comment]
This was fixed with #157
