### ISSUE TITLE
Intersection allowed to contain more than one class and Any

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#13]
IDEBUG-231
 Possibly a child item for [IDE-385|https://jira.numberfour.eu/browse/IDE-385]

Currently, intersection type violate Constraints 23.1 (any may not be contained in intersection) and 23.3 (intersection may contain only one class).

```
class A{}
class B{}

// Constraints 23.1 XPECT FIXME errors --> "Any must not be an element of intersection type" at "{any,A}"
var intersection{any,A} b;

// Constraints 23.3 XPECT FIXME errors --> "Only one class may be contained in the intersection type" at "{A,B}"
var intersection{A,B} a;

```

**Comment by mor-n4** [comment]
In this context, also consider the following example:

``` javascript
// example 1
class A {}
class B {}

function <T extends B> getB(): T {return null;}

var a: A;
a = getB();
```

N4JS does not show an error in the last line, whereas Java would show an error (in corresponding code).
Note however that also Java does not show an error if at least one of types A, B is an interface:

``` java
// example 2
public class TestJava {

    static class A {}
    static interface B {}


    static <T extends B> T getB() {
        return null;
    }


    public static void main(String[] args) {
        A test;
        test = getB(); // no error in Java
    }
}
```

Even if, in the above Java example, class A is made final, Java does not show an error (which seems slightly inconsistent and is a hint that N4JS's handling of example 1 need not necessarily be seen as a bug).

**Comment by mor-n4** [comment]
As another consideration: if all "empty" intersection types are to be delcared illegal, then we would have to check much more than just class vs. interface or final vs. non-final. Consider:

``` javascript
class ~A {
    public prop: string;
}
interface B {
    public prop: string;
}
class C {
    public prop: number;
}

var test1: intersection{A,C}
var test2: intersection{B,C}
```
