### ISSUE TITLE
Incremental build takes forever

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#134]
IDEBUG-738

When doing a change in a base class of a large project, the incremental build takes forever, much longer than a clean build of the whole workspace.

**Comment by JensN4** [comment]
Also see duplicate https://github.com/NumberFour/n4js/issues/145
with concrete (at least on my machine) reproducible case.

**Comment by JensN4** [comment]
as discussed: split pr, only push some bug fixes but NOT new affect-analysis. Instead, create a follow up for the latter.

**Comment by kittaakos** [comment]
> Instead, create a follow up for the latter.

https://github.com/NumberFour/n4js/issues/175
