### ISSUE TITLE
Need access on the projectNameMapping

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#137]
IDEBUG-466

Currently only the node execution spawned from IDE carries projectNameMapping as part of the global $executionData.
The problem is that this information is not available when running the code from command line (or deployed to a server).

Suggestion: Dump it to the file system so it can be picked up by the server.

**Comment by mor-n4** [comment]
after discussion with @dbo:
- solution could be to write the project name mapping into a file in JSON format when launching n4js code from the IDE
- not very important at the moment
- will change to "enhancement", as this is more like a new feature / improvement

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/596
