### ISSUE TITLE
Implementing interfaces before extending base class causes warning with odd message

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#138]
IDEBUG-784

For example in this case:

```
class A {}
interface I {}

class B implements I extends A  {   
}
```

you get a warning:
Use comma (",") instead of keyword "extends". This warning will become an error soon!

Perhaps an error instead of a warning and a quickfix to rearrange?

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/595
