### ISSUE TITLE
Unknown types shown in outline view of built-in library

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#149]
In a test project using mangelhaft, I opened the module Assert. In the outline, a lot of "unknown" types are shown. See screenshot.
![screen shot 2016-03-25 at 12 39 54](https://cloud.githubusercontent.com/assets/1913837/14043680/22e99a7a-f287-11e5-848b-a914912eb9df.png)
There must be no unknown types!

Note that re-loading the built-in libraries does not solve that problem.

**Comment by lbeurerkellner** [comment]
The issue is more general since the outline fails to display any type information for non-trivial type expressions e.g. union, intersection, function, arrow function, constructor, type
