### ISSUE TITLE
Eclipse based N4JS workspace should be reviewed wrt the project nature

### ISSUE THREAD

**Issue by kittaakos** [NumberFour/n4js#153]
Currently there are no project nature checks when retrieving project references and/or source containers from the N4JS Eclipse based workspace. That means any accessible generic Eclipse projects are accepted and treated as an N4JS project via the N4JS workspace. Review the logic at 

<pre>
eu.numberfour.n4js.ui.internal.EclipseBasedN4JSWorkspace.getLocation(URI, ProjectReference, N4JSSourceContainerType)
</pre>

This can be tricky and could cause issues when querying and setting the <tt>IProject#getDynamicReferences()</tt> of a project. To prove that this is an actual problem one can check with the below simple test in the <tt>RunExternalLibrariesPluginTest</tt>.

<pre>
    @Test
    public void runClientWhenWorkspaceProjectsAreNonN4jsProjects() throws Exception {

        for (final String libProjectName : LIB_PROJECT_IDS) {
            getProjectByName(libProjectName).delete(true, new NullProgressMonitor());
        }
        waitForAutoBuild(false);

        final ProcessResult firstResult = runClient();
        // @formatter:off
        assertEquals("Unexpected output after deleting all library projects from the workspace: " + firstResult,
                "External A<init>" + NL +
                "External B<init>" + NL +
                "External C<init>" + NL +
                "External D<init>" + NL,
                firstResult.getStdOut());
        // @formatter:on

        for (final String libProjectName : LIB_PROJECT_IDS) {
            final IWorkspaceRoot root = ResourcesPlugin.getWorkspace().getRoot();
            final IProject project = root.getProject(libProjectName);
            assertFalse("Expected non-existing project: " + project, project.exists());
            project.create(new NullProgressMonitor());
            assertTrue("Expected existing project: " + project, project.exists());
            assertFalse("Expected non-accessible project: " + project, project.isAccessible());
            project.open(new NullProgressMonitor());
            assertTrue("Expected accessible project: " + project, project.isAccessible());
        }
        waitForAutoBuild(false);

        final ProcessResult secondResult = runClient();
        // @formatter:off
        assertEquals("Unexpected output after creating non-N4JS projects in the workspace: " + secondResult,
                "External A<init>" + NL +
                "External B<init>" + NL +
                "External C<init>" + NL +
                "External D<init>" + NL,
                secondResult.getStdOut());
        // @formatter:on
    }
</pre>

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/592
