### ISSUE TITLE
Let/const on top-level are transpiled to var

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#159]
The code

``` javascript
let msg = 'hello';
console.log(msg);
```

will be transpiled to

```
(function(System) {
    'use strict';
    System.register([], function($n4Export) {
        var msg;
        return {
            setters: [],
            execute: function() {
                msg = 'hello';
                console.log(msg);
            }
        };
    });
})(typeof module !== 'undefined' && module.exports ? require('n4js-node/index').System(require, module) : System);
```

i.e. the let is turned into a var which is being hoisted. This is probably a left-over of old hoisting logic and is probably unintended.

This happens only on top level, so the following transpiles as expected:

``` javascript
{
    let msg = 'hello';
    console.log(msg);
}
```

Note that a rewrite to "var" makes a difference. For example, the following N4JS code will currently print "undefined" (with the current N4JS transpiler), but according to ES6 it should throw a ReferenceError at runtime:

```
console.log(msg);
let msg = 'hello';
```

(side note: the fact that the runtime error is not validated yet is a seperate issue and a known limitation: we do not yet validate the Temporal Dead Zone of let/const).

**Comment by torstenkraemer** [comment]
Will consider exported const/let declarations.

**Comment by torstenkraemer** [comment]
After some investigation I sadly have to say, that a rewrite in the current transpiler is not possible.

Consider this code:

``` javascript
var msg = 'hello';
function out(){console.log(msg);};
out();
```

which will be transpiled to 

``` javascript
(function(System) {
    'use strict';
    System.register([], function($n4Export) {
        var msg, out;
        out = function out() {
            console.log(msg);
        };
        return {
            setters: [],
            execute: function() {
                msg = 'hello';
                out();
            }
        };
    });
})(typeof module !== 'undefined' && module.exports ? require('n4js-node/index').System(require, module) : System);

```

So having `let msg=...` in this example we would obviously still be required to hoist the `msg` declaration.  The only difference we could make is to keep a separate `let` declaration block beside the var-declaration block and thereby not changing msg to a `'var`. 
But there is no benefit in this.

**Comment by torstenkraemer** [comment]
Closing this as won't fix, for now. 
Improvements may be achievable in a broader scope working on https://jira.numberfour.eu/browse/IDE-1023 .
