### ISSUE TITLE
Remove (@)@ImplementedBy annotations and related processing

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#16]
IDEBUG-242
 Given a project-definition with source file src/A, src/ObjectExtension.n4jsd and an external definition ext/ObjectExtension2.js with 

manifest.n4mf config:

```
...
Sources {
    source { 
        "src"
    }
    external { "ext" }
}...
```

ext/ObjectExtension2.js

```
var MObject = function MObject () {
        this.m = function() {
            console.log( "called m on MObject from ObjectExtension2.js")
        }
    }

module.exports = {
    "MObject": MObject
}
```

src/ObjectExtension.n4jsd   // note: missing "2" !

```
@@ImplementedBy("ObjectExtension2")
export external public class MObject {
    m();
} 
```

And consuming class src/A 

```
import MObject from "ObjectExtension"

class A extends MObject { }
var MObject m = new A();
console.log( m );
m.m();  // <-- expecting called m on MObject from ObjectExtension.js
```

We get an runtime-error since the @@ImplementedBy Annotation is not evaluated in the generation of A. 

A.js wrongly links to the naming-convention-file called ObjectExtension.js instead of ObjectExtension2.js 

Hmm... makes we wonder if we should allow @ImplementedBy per element... and how to deal with naming conventions defined in the manifest (whatever that means by now...)
We have to review 12.1.3 and provide proper tests.

**Comment by torstenkraemer** [comment]
Thorough investigation revealed, that the `@@ImplementedBy`and `@ImplementedBy` annotations are a) not used at all and b) not supported by the transpiler. As this exotic feature would complicate the handling of transpiled code, we decided to remove it entirely. 

The existing naming convention - an implementation of X.n4jsd is named X.js and located in an 'external' marked  folder of the project - seems to be sufficient.
