### ISSUE TITLE
Partial highlighting in 'New Class Wizard' (and related UI) is black on black on Windows.

### ISSUE THREAD

**Issue by torstenkraemer** [NumberFour/n4js#161]
In the UI of the New Class Wizard and related dialogs some parts of text-input sections are highlighted in a different way: 
(Hint look at the content of the text-field labeled with "Module" or "Module Specifier".
On Mac OS:  
![screen shot 2016-04-12 at 09 12 44](https://cloud.githubusercontent.com/assets/7485988/14452420/ca0672a0-008e-11e6-909f-a178e14f09fa.png)
and on Windows 10:
![screen shot 2016-04-12 at 09 05 22](https://cloud.githubusercontent.com/assets/7485988/14452476/24c64544-008f-11e6-9dfe-a655d8391de5.png)

**Comment by yoosiba** [comment]
dupicates #128

**Comment by lbeurerkellner** [comment]
This was fixed with #157
