### ISSUE TITLE
ambiguity in module specifiers / qualified names

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#162]
Based on the bug #158 consider following:
- project with this data in the manifest

```
ArtifactId: foo.bar.baz
Sources {
    source {
        // file://..../foo.bar.baz/src/foo/bar/baz
        "src/foo/bar/baz"
    }
}
// file://..../foo.bar.baz/src/foo/bar/baz/some/deep/path/to/module.n4js
MainModule: "foo/bar/baz/some/deep/path/to/module"
```
- to import from `module.n4js` clients may use

```
import * as nP from "foo.bar.baz"; project import
import * as nC from "foo.bar.baz/foo/bar/baz/some/deep/path/to/module"; complete import
import * as nS from "foo/bar/baz/some/deep/path/to/module"; simple import
```

Looking at raw value of the in the import statement it looks like it is easy to distinguish when it refers to concrete project, but it is only the case when project name contains dots. In other cases first segment of the module specifier is not distinguishable from project name. That requires extra logic of lookups and leaves some space for collisions and undesired behavior (e.g. clash between project `A` and module `A`). Currently (in scoping) we favor projects over modules in case of clashes. 

This is potential for many bugs in our system. If it was scoping only, maybe we could live with some fallbacks and hidden logic, but if we consider other parts of the system (compilation, whole type system, validations content assist ... ) where module specifiers and qualified names are used it becomes a problem.

Consider following not one-to-one transformations of the module specifiers and qualified names we do:
- `QualifiedName` is supports only one separator, by default it is dot `.`
- `IQualifiedNameConverter.DefaultImpl` supports only one separator, by default uses dot `.`
- `SpecifierConverter` (extends one above) supports only one separator, overrides default to the slash `/`
- `ModuleSpecifierValueConverter` changes all slashes with dots (`toValue()`) , and back (`toString()`).
- In several places we do `project.projectName.replace(".", "_")`
- In several places we do `qualifiedName.replace(".", "/")`

Clarify semantics of the qualified names and module specifiers.
Align implementation.
Remove hacks.

**Comment by JensN4** [comment]
Part of IDE-2227

**Comment by yoosiba** [comment]
see bugfix for imports only in #158
