### ISSUE TITLE
Organize imports doesn't work for default exports

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#166]
Create one module A.n4js:

``` js
export default public class A {}
```

while another B.n4js has the code:

``` js
class B extends A {}
```

Trying "organize imports" (cmd+shift+o on mac) doesn't add te missing import statement.

**Comment by torstenkraemer** [comment]
Organise imports can't work for default exports:

Having a default-export in module A as above will never expose the name of the class. 
So, when organising the imports of B.n4js, then a class "A" is not found in the index (not exported with that name and you cannot import it with that name).
So `extends A` in B.n4js could mean:
- A is a typo  
- A is an missing alias for an missing default import -- but then it could have come from any file that offers a default export of an classifier.

So imagine in your projects you have a couple of hundred modules exporting default-classes, some of them with the same name, e.g. "A.n4js" in different subfolders: "a1/A.n4js", "a2/A.n4js".  
Then it is hard to choose...

What is your concrete expectation? 
How shall we change the organise import?

**Comment by dbo** [comment]
If there are multiple classes named A, then we have to choose for the correct one anyway, even today. I expect there's a nominal type A known (I expect we have an FQN for that type, if you look at A.n4type.fqn will you get `A.A`?). The import statement should import it using the default notation, since it's exported like that.

**Comment by JensN4** [comment]
What we could do:
- organize imports also considers modules with same name as used in reference, and if such a module contains a default declaration with (meta) type matches then it is considered as well
