### ISSUE TITLE
compiler does not preserve paths

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#17]
IDEBUG-244
 compiler strips "source" and "test" path fragments, as a result source fragments and test fragments are mashed together in the output folder.

This makes output folder to be mix of 'production' code and 'test' code.

Additional side effect is that files with the same name on top level of source and test fragments (so with the same name but different path) will conflict with each other. Conflict will result in silent overwriting of the files by builder either in random order (depends on internal builder  discovery) or in order of user edits (last one edited overwrites older one). 

As a user I would expect that there is distinction between source and test fragments in output folders (or two separate folders).

Attached screenshot presents configuration (manifest file), and project structure  including issue in output folder.

also, when test fragment is outside {{src}} path then it is not compiled. 
Example config:

```
Sources {
    source { 
        "src"
    }
    test { 
        "test"
    }
}
```

This issue manifests itself also with generated files, for example If we have {{Foo.xml}} generator generates some tests for that value object. Also User might want to write some tests for that type.
Most typical name used in both cases is {{FooTest}}. This course compilation error if we have {{test/n4js/FooTest.n4js}} and {{test/n4js-gen/FooTest.n4js}} and project manifest is defined as 

```
Sources {
    test { 
        "test/n4js",
        "test/n4js-gen"
    }
}
```

**Comment by yoosiba** [comment]
invalid, in new codebase there is validation for duplicated modules
