### ISSUE TITLE
Investigate and analyze the number of affected resources in the incremental builder

### ISSUE THREAD

**Issue by kittaakos** [NumberFour/n4js#175]
Currently the incremental builder (our custom <tt>ClusteringBuilderState</tt> implementation) is too greedy and in some cases queues and rebuilds much more resources than it would be required when modifying the <tt>TModule</tt> of one single resource. Come up with a resource affect analysis and **try to reduce the number of queued resources** to improve performance and user experience.

Consider the followings:

<ul>
<li>After invalidating the serialized <tt>TModule</tt> information of a delta (by wrapping into a custom resource description delta) the delta will always represent a change.</li>
<li>Try to ignore the above described wrapping mechanism.</li>
<li>Consider checking transitive project dependencies when deciding whether a delta is affected by an other resource description.</li>
</ul>

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/591
