### ISSUE TITLE
n4jsc.jar should manage npm install location

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#176]
as a follow up to #165 the n4jsc.jar should mange npm install location in following way:
1. if it does not exist and `--targetPlatformSkipInstall` is not specified, location is created
2. if it does exist and `--targetPlatformSkipInstall` is not specified, delete contents of that location if any
3. if it does not exist and `--targetPlatformSkipInstall` is specified, proceed
4. if it does exist and `--targetPlatformSkipInstall` is not specified, proceed

Note that options `#3` and `#4` are not the usual use cases. Their behavior depends on circumstances (e.g. developer prepares build manually).
In any case exceptions will propagate up and terminate n4jsc.jar invocation (i.e. n4js build process).

**Comment by dbo** [comment]
I think you can combine them generally to:
If `--targetPlatformSkipInstall` is not set:
1. If the target folder exists, remove its contents.
2. If the target folder does not exist, create it, including any missing folder.

**Comment by yoosiba** [comment]
yup.
Also there is also git clone behavior for `n4jsd` files (which lands in the install location) but invocation of that depends on `--targetPlatformSkipInstall` anyway.
