### ISSUE TITLE
Content assist mangels imports in certain cases

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#177]
If you have a file with a top level comment and an import beneath it like:

``` javascript
/*
 * party 
 * time
 * always
 */
import { Precondition } from "n4/mangel/precondition/Precondition"
 export public class Whodunnit {
     public notMe() {

     }
 }
```

and you use content assist to import a module from within a method the import gets put in the wrong place. see it in action here
![example](https://cloud.githubusercontent.com/assets/417616/14856181/58f1771c-0c97-11e6-8a91-9c0dde947ee1.gif)

**Comment by yoosiba** [comment]
On windows it is also bad, but different :   auto-complete jumps to a new position, but no import is inserted.

![33](https://cloud.githubusercontent.com/assets/944287/14857843/fb153f64-0c9d-11e6-9712-325bb5fafc4e.gif)

**Comment by yoosiba** [comment]
looks related #92

**Comment by torstenkraemer** [comment]
First example now works. @yoosiba would you try your example, please.

**Comment by torstenkraemer** [comment]
Duplicate of #92

**Comment by yoosiba** [comment]
My test case is also working.
