### ISSUE TITLE
For parameterized tests we need @Parameters and @Parameter annotations

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#178]
For parameterized tests (similar to [junit](https://github.com/junit-team/junit4/wiki/Parameterized-tests)) we need some annotations to mark the static method that gives the list of lists of parameters as well as to mark the fields that will get the parameters injected in.
#### @Parameters(["name template"])

Ide should restrict to just static methods.
Ide should error if more than one `@Parameters` annotation is used per class
Method must return an `Iterable<Iterable<? extends any>>`
#### @Parameter([int])

Ide should restrict to just instance fields/setters;
if no details default to index 0 (like junit)
ide should error if the same index (including default) is used more than once 
ide should error if details is provided but is not a single integer representing the index of the parameter array for parameter.

if index is out of range of the parameters array the field will not be initialized.

**Comment by kittaakos** [comment]
Maybe you can clarify what are the expectation when there is a class inheritance chain between test classes, to be more precise, for instance how we should we handle super class fields (private, protected, and public ones as well) with <tt>@Parameter</tt> annotations in the subclasses. Also, should we consider abstract classes as well? And last but not least what if parameter fields are overridden in subclasses?

**Comment by arrowplum** [comment]
`@Parameter` should have the same behavior as `@Test` except for being for fields (should respect super classes [including abstract classes] and interfaces). Does that sound right?

**Comment by mor-n4** [comment]
I added the two annotations; but validations, etc. are pending.

**Comment by yoosiba** [comment]
annotations available in eclipse/n4js
