### ISSUE TITLE
Declared type of the CatchVariable is ignored

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#179]
It is allowed in N4JS to declare type of a CatchVariable, see grammar:

```
CatchVariable <Yield>:
        =>bindingPattern=BindingPattern<Yield>
    |   =>(name=BindingIdentifier<Yield> -> ColonSepTypeRef)
    |   name=BindingIdentifier<Yield>
;
```

But type is always inferred to `any`, see type rule:

```
axiom typeCatchVariable G |- CatchVariable catchVariable:
    if (JavaScriptVariant.getVariant(catchVariable)===JavaScriptVariant.n4js) {
        G.anyTypeRef
    } else { // plain JavaScript
        G.anyTypeRefDynamic
    }
```

Which leads to unexpected `Couldn't resolve reference to IdentifiableElement 'X'` error, see screenshot.
![catchvariabletype](https://cloud.githubusercontent.com/assets/944287/14885717/3f92d868-0d4d-11e6-9b28-fde5cdb1fe09.PNG)

Please align type system with grammar, or grammar with type system, or add validation forbidding type declaration.

**Comment by JensN4** [comment]
We need to remove the type annotation in the catch variable, as we cannot check that. 
Alternatively the transpiler could emit an instanceof check, but I do not really like that...
