### ISSUE TITLE
N4Class.of oddities

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#18]
IDEBUG-258
 N4Class.of works for instances, but not class types, i.e.

```
class Foo {}

N4Class.of(new Foo()).name // works
N4Class.of(Foo).name // crashes
```

static method {{of}} is to be used on instances of classes, on types property {{n4type}} should be used.

```
class Foo {}
console.log(Foo.n4type.name)

var foo = new Foo();
console.log(N4Class.of(foo).name)
//or
console.log(N4Type.of(foo).name)
```

issue in your example I see is that {{N4Class.of(Foo)}} is valid usage, but misleading one. That case is basically {{Foo.constructor.n4type}}. {{Foo}} is function, its {{constructor}} is a js function, and js functions have no {{n4type}} property, hence undefined.

N4Class.of should be able to cope with both Object and type{?}.

**Comment by mor-n4** [comment]
see also #81

**Comment by mor-n4** [comment]
doing this together with #81
