### ISSUE TITLE
Wildcards for module filters don't work with "dot" folders

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#182]
Wildcards module path specifiers  fo module filters don't work with "dot" projects as sources.
![wildcarddot](https://cloud.githubusercontent.com/assets/944287/14952164/6a424fb2-105e-11e6-9e08-03d04e802240.PNG)
also when source path is explicitly provided
![wildcarddotin](https://cloud.githubusercontent.com/assets/944287/14952167/6e9de60c-105e-11e6-9201-ec906e3ee7d6.PNG)

In either case error message is `Module specifier ** doesn't exist.`

**Comment by JensN4** [comment]
also see #239

**Comment by yoosiba** [comment]
cannot reproduce in eclipse/n4js
