### ISSUE TITLE
@Placeholder annotation needed to write code before real annotation is implemented

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#185]
#### The problem:

Sometimes we need new annotations for features we are writing. Until we have custom annotation support, the _minimum_ turnaround for a new annotation is 1 day iff the ide team high prios adding it and iff there is a new build.
#### Proposal:

a `@Placeholder(ID, [anything])` annotation that can be added at any location annotations can be added. This annotation should not change any behaviour but should be queryable at runtime from n4js.

The ID will allow for a grep replace once the real annotation is in place. The optional second parameter should allow for any extra info the real annotation would take.

**Comment by arrowplum** [comment]
Any word on this. The hacks in our code to get around the fact that we can't add custom annotations increase. If we aren't going to get decorators in the next few weeks at least this. I have been told that adding annotations takes an hour or two so...

**Comment by mmews-n4** [comment]
@arrowplum For which annotations are workarounds already implemented? I found the following open annotation issues:
* `@SuppressWarnings` https://github.com/NumberFour/n4js/issues/343
* `@Parameters` and `@Parameter` https://github.com/NumberFour/n4js/issues/178
* `@LimitReflection` https://github.com/NumberFour/n4js/issues/31

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/589
