### ISSUE TITLE
N4JSPostProcessor might not expose all internal types that need to be exposed

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#188]
Method N4JSPostProcessor#exposeReferencedInternalTypes() might not expose all internal types that need to be exposed, because it does not seem to check transitive references.

For example: given a TModule with a type A in topLevelTypes and types B, C in internalTypes, with A referring to B, B referring to C, then C should be exposed because it is referred to by the exposed and thus publicly visible internal type B. But this does not seem to be done.

(note: did not check this yet with an example; just noticed this while looking at the code; to be verified)

**Comment by JensN4** [comment]
We have to look at that issue in the context of improving the incremental builder.

**Comment by yoosiba** [comment]
@mor-n4 was resolved at least for the structural types (see 9e2fcd3e17981ef8087adba6d11fd4f47d2e40a8).
Is this issue still valid? Or could you provide example where this is still an issue?

**Comment by mor-n4** [comment]
probably it's fixed by @yoosiba 's changes; but I'll have another look at this

will assign this to me and set it to in progress, so I can have a look at it next week ...

**Comment by yoosiba** [comment]
@mor-n4  can you confirm if it is fixed in elicpse/n4js ?

**Comment by mor-n4** [comment]
@yoosiba working fine!

Verified with:
```javascript
const v0 = {prop: 'yup'};
const v1 = {prop: v0};

export public const v9 = v1;
```
and
```javascript
const v0: ~Object with {prop: string} = null;
const v1 = {prop: v0};

export public const v9 = v1;
```
In both cases both internal types are moved to `exposedInternalTypes`.

Closing as fixed.
