### ISSUE TITLE
Inconsistent error behavior in UserdataMapper in case of errors in source code

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#193]
If the source code of an N4JS resource contains errors (typos, etc.), method `#createUserData(TModule)` in `UserdataMapper` has a slightly inconsistent error handling:
- errors leading to an unresolvable proxy in the TModule: no TModule is persisted to the Xtext index, even if it might be 99% correct (instead, a dummy "timestamp user data" is created)
- other errors (e.g. plain validation errors, unresolvable proxy in AST only): TModule is persisted to the Xtext index, even if it might be broken or invalid due to the error

Overall, the second behavior seems to make more sense, because we do not want to lose all type information in case of maybe small, minor errors. Also, the first behavior won't save other ResourceSets (e.g. in another editor) from seeing the unresolvable proxies, anyway, because the other ResourceSet will demand-load the resource from file if it is not found in the index, and will thus have to deal with the unresolvable proxies anyway. In case of the dirty-state index, it will mean that - depending on the error type above - other ResourceSets will suddenly see the file on disk, not the dirty state anymore, which seems even more inconsistent.

Therefore, it should be checked if it makes sense to remove the following code from `#createUserData(TModule)` in `UserdataMapper`:

```
        originalResource.performPostProcessing();
        if (EcoreUtilN4.hasUnresolvedProxies(exportedModule) || TypeUtils.containsDeferredTypeRefs(exportedModule)) {
            // don't write invalid TModule to index
            return createTimestampUserData(exportedModule);
        }
```

In any case, add tests and thoroughly document the handling of erroneous resources in the design document (in particular w.r.t. to the Xtext index).

**Comment by mor-n4** [comment]
note: the case of having DeferredTypeRefs in the TModule can probably be handled more rigidly (try to fail-fast in that case, i.e. throw exception)

**Comment by yoosiba** [comment]
@mor-n4  can you confirm if it is fixed in elicpse/n4js ?

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/588
