### ISSUE TITLE
Clarify usage of declared functions as types

### ISSUE THREAD

**Issue by torstenkraemer** [NumberFour/n4js#204]
Given a function 
`function foo() :string { return null; };` 
Currently one can write a second function: 
`function meta( p1 : foo ) :string {...}` which should be written using a type expression:
`function meta( p1 : {function ():string}):string {...}`.

A validation should enforce the use of function type expressions and disallow function names as type-aliases.

A more obvious example arises if the function is parameterised:
`function <T> z() : T { return null; };`
Currently the language accepts:
`function meta( p1 : z<string> ) :string {...`
which at least should be 
`function meta( p1 : <string> z ) :string {...` if allowed at all.

**Comment by yoosiba** [comment]
It is super inconvenient to write functional code in N4JS, especially when taking higher-order functions into mind. For example having following `bar` and `baz`, defining `foo` which takes `bar` and returns `baz` is a pain.

``` javascript
function bar( p1 : number, p2 : number ) : string {/**/}
function baz( p1 : string, p2 : string ) : string {/**/}
function foo (fpar : {function ( number, number ) : string}) : {function ( string, string ) : string } {/**/}
```

Also when changing in bar or baz signature type system will not very helpful.

It would be good to provide type expressions syntax to use named function types, e.g.

``` javascript
function foo (fpar : Function{bar}) : Function{baz} {/**/}
```

This could allow better error messages from type system , e.g.:

``` javascript
function bar( p1 : number, p2 : number ) : string {/**/}
function baz( p1 : string, p2 : string ) : string {/**/}
function foo (fpar : Function{bar}) : Function{baz} {/**/}
function qux( p : boolean ) : any {/**/}

//XPECT type error --> "Function{qux} is not subtype of Function{baz}" at "foo(qux(true))"
foo(qux(true));
```

**Comment by mor-n4** [comment]
after discussion with Jens:
probably we do not want to disallow this with a validation but instead support it (most should be supported already out of the box; but check this and add tests if missing)

note: functions are types

Question: what about (static / non-static) methods?

**Comment by mor-n4** [comment]
as part of #285 a validation was added to disallow this, but only because it is not fully supported, at the moment. The validation should be removed once full support is implemented as part of this task.

**Comment by mor-n4** [comment]
when implementing full support, consider this example:

```
function foo(n:any) {}
let f: foo;
let f2: Function = f; // shows error: "foo is not a subtype of Function." at "f"
```

The problem is that the parser creates a ParameterizedTypeRef for the type of `f` but according to our types model it should be a `FunctionTypeRef` if the declared type is a TFunction. For more details see #285

**Comment by JensN4** [comment]
Decision: We absolutely want to support that. Just like a class declaration defines a type, a function declarations defines a type as well. Only difference: In the first case it is a class type, in the second one a function type.

This is related to #210 -- in combination with "abstract" function declarations we are then able to support "named" function types without the need of additional constructs.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/587
