### ISSUE TITLE
Static polyfill not working with type parameters having recursive upper bounds

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#205]
A (probably) bogus error is showing up when tryping to define a static polyfill for a class that has type parameters with recursive upper bounds.

Filled module:

```
@@StaticPolyfillAware

export public class ToBeFilled<T,S extends T> {}
```

Filling module:

```
@@StaticPolyfillModule

@StaticPolyfill
export public class ToBeFilled<T,S extends T> extends ToBeFilled<T,S> {} // error: "S is not a subtype of T." at "S"
```

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/585
