### ISSUE TITLE
Declared function types à la typescript

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#210]
To use common function types we need to be able to declare function types. 
We should use the TypeScript syntax:

``` typescript
interface NumberCallback {
    (n: number): string;
}

class BlastFurnace {
    blast (blastNum: number, callback: NumberCallback) : string {
        let blastString: string = callback(blastNum);
        return blastUm;
    }
}
```

**Comment by yoosiba** [comment]
maybe use java8 annotation
http://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html

**Comment by JensN4** [comment]
or "abstract" functions:

```
abstract function NumberCallback(n: number): string;
```

or (if this this is too complicated for parser

```
@Abstract function NumberCallback(n: number): string
```

since the following is already supported:

```
function NumberCallback(n: number): string { return ""}

class BlastFurnace {
    blast (blastNum: number, callback: NumberCallback) : string {
        let blastString: string = callback(blastNum);
        return blastString;
    }
}
```

That is, the (abstract) function defines the function type, which can be used already. The "only" thing we have to assure now is that the abstract function is not used as an identifier ref (i.e., only as type ref).

**Comment by kduske-n4** [comment]
Why not just

```
function NumberCallback(n: number): string;
```

or, even better

```
function NumberCallback(number): string;
```

since the argument names are irrelevant in this context. Also, this would be more inline with function type declaration expressions such as when they are used as type arguments:

```
class  A<Z extends {function (number): string}> {s : string}
```

**Comment by yoosiba** [comment]
Note that when you define function type with simplified function syntax, you cannot express function properties. Functions in JS are objects, can have fields and methods. None of the approaches with syntax like `function f():void` allows to express that. Using interface with annotation allows to model that.

Alternatively you could allow annotation on function definition. That annotation would refer to the type (interface) which would model function properties. This way you have concise function definitions and possibility to model its object nature.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/584
