### ISSUE TITLE
Union property access not working properly for constructors

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#219]
If a union has a ConstructorTypeRef as a member, the property access gets confused:

``` javascript
class A {
    static field: string;
    static get getter() { return null; }
}

// works fine:

var ctor: constructor{A};
// XPECT noerrors -->
ctor.field;
// XPECT noerrors -->
ctor.getter;


// does not work properly:

var ctorUnion: constructor{A} | ~Object with { field:string; getter:any }
// XPECT FIXME noerrors --> "Member field not present in all types of union or incompatible."
ctorUnion.field;
// XPECT FIXME noerrors --> "Union combines fields and getters with name getter and therefore property getter is read-only."
ctorUnion.getter;
```

Also make sure it works for ClassifierTypeRefs!!

**Comment by JensN4** [comment]
I'd assume the problem is that static members of a class become instance members of the constructor. Apparently we do not correctly handle that in all cases.

Why did you set prio to "high"? Is it required at the moment?

**Comment by JensN4** [comment]
OMG... this bug revealed a bigger problem: We create member scopes with a static access flag. And then we again pass static access flags to every method. And then, in certain cases, we again check the static modifier of members later on. This makes it almost impossible to "change" the static access strategy in case of classifier types. We should think about removing all these static access checks and only use the static access flag which has been past to the scope at creation. But I'm not quite sure whether that would work correctly... hmm... maybe I found a solution though ;-)

**Comment by JensN4** [comment]
Oh.. and we also have another problem:

```
class A {}
// wrong result: constructor{A} XPECT FIXME type of "x" --> constructor{Function}
var x = A.constructor;
```

**Comment by JensN4** [comment]
And another follow-up:

```
var t : ~Object with { x: string};
// XPECT FIXME errors --> "constructor not defined..." at "constructor"
t.constructor;
```

(already defined in spec, cf. Constraint 70, a2)
We maybe could assume that all instances have the "constructor" property, but we cannot type it....

**Comment by JensN4** [comment]
and

```
var t2: ~Object with { constructor: string};
// XPECT noerrors --> 
t2.constructor;
```

which is not accepted by the parser at the moment... Will fix that, we can later discuss if we want to allow that or add a warning.

**Comment by JensN4** [comment]
and

```
class A {
    private s;
}

var a: A;
// XPECT noerrors -->
a.s;

var u: union{A};
// XPECT FIXME noerrors -->
u.a;
```

Unfortunately, we have several wrong expectations....

**Comment by JensN4** [comment]
So, I refactored union type access in general and slightly improved error messages. If a member is contained in all elements of the union, but not accessible to different reasons, these reasons are now printed out.
