### ISSUE TITLE
Issue with the new array syntax ([ ]) and the wildcard character (?)

### ISSUE THREAD

**Issue by chanakyabhardwajj** [NumberFour/n4js#220]
The following code is not getting validated.
`(a: [int]?) => {}`

**Comment by mor-n4** [comment]
note: this problem will become obsolete, once we have added support for ES6 default initializers for formal parameters (see https://jira.numberfour.eu/browse/IDE-1345) because that will replace our current `?` syntax for optional fpars

**Comment by mmews-n4** [comment]
fixed. New syntax is `(a: [int]=) => {}`
