### ISSUE TITLE
Open-N4JS-Type from library does not reveal location

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#223]
Let M be a module containing a type opened via "Open N4JS Type".

If M is located in a library, the "link with editor" in the Project Explorer does not work. 

If M is contained in a library required by at least one project. In that case, the referenced file (in External Libraries) should be opened

In any case, the full name (library name + path in the library) should be shown in the Eclipse title, as it is done with all other files.

**Comment by yoosiba** [comment]
cannot reproduce in eclipse/n4js
(linking works, library name and location visible in the bottom of the open type dialog)
