### ISSUE TITLE
Error reporting of AbstractSubGenerator falsely treats OperationCanceledException as an error

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#228]
When the auto-build is canceled while the transpiler is running, the error reporting in method `eu.numberfour.n4js.generator.common.AbstractSubGenerator#doGenerate(Resource, IFileSystemAccess)` will add a `Severe problem detected in compiler` error marker to the workspace. But for an `OperationCanceledException` this does not make sense.

Probably the fix is very easy and we just have to ignore this exception type in the catch-block of above method. However, it should be double checked that the `AbstractSubGenerator` (or its clients, e.g. the incremental builder) properly deal with the cancellation during transpilation.

**Comment by mor-n4** [comment]
set prio to high because the false error markers can be extremely misleading for the end user

**Comment by mor-n4** [comment]
possibly related:
https://github.com/NumberFour/n4js/issues/63

**Comment by mor-n4** [comment]
hint for debugging this:
set a break point somewhere in the transpiler; go to product, edit, save -> break point will be reached; without hitting continue in the debugger, go again to product do another edit and save again -> will block product, send cancel event to transpiler that is still suspended at the break point

**Comment by JensN4** [comment]
Hmm.. I ran into that problem as well... but I'm not so sure about a possible solution. Fact is: Cancelation means that the JS file has not been properly built, has it? We do not want to have no error when the JS file is not there, do we? Actually I do not know a proper solution. I agree that an error in the n4js file is odd...

**Comment by mor-n4** [comment]
the main reason for the cancelation is that a new incremental build is being started; in that case the partially built file will immediately be re-built. Or, if the user manually cancels an auto-build, it should be expected that files are incompletely built. Compare with the situation that auto build is turned off: then many files might be out-dated but still we do not expect error markers for all these files.
THe main thing we have to make sure is that any partially built output file is not treated as a properly built file but instead treated as outdated and being rebuilt in any future build (auto or manual).
