### ISSUE TITLE
Type variables in Classifier- and ConstructorTypeRef allow any kind of type to show up as property staticTypeRef

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#229]
Because `constructor{T}` is allowed (with type variable T) any kind of type reference can end up in the ConstructorTypeRef:

```
class B {}
class C {}

enum Color { RED, GREEN, BLUE }

class G<T> {
    ctor: constructor{T};
}

var gb0: G<? extends B>; // <-- this case is fully supported since end of June 2016
var gb1: G<B|C>;
var gb2: G<~B>;
var gb3: G<type{B}>;
var gb4: G<constructor{B}>;
var gb5: G<Color>;
var gb6: G<number>;

class Other {
    m(): G<? extends this> {return null;}
}
var gb7 = new Other().m(); // type of gb5 will be "G<? extends this[Other]>"
```

Especially `constructor{constructor{B}}` seems odd. We either have to support all the above cases properly (both conceptually and in the implementation) or disallow type variables in `type{X}` and `constructor{X}`.

NOTE: case `gb0` above is properly supported since end of June 2016, see
https://github.numberfour.eu/NumberFour/n4js/pull/105

**Comment by mor-n4** [comment]
Solution idea: maybe we could allow, conceptually, any kind of type reference for X in `constructor{X}`. If X is a type that does not have a constructor (e.g. interfaces, enums, etc.), we could handle this similarly to "empty" intersections (e.g. intersection of two unrelated classes, intersection of two primitives): as an empty type for which no value exists. If the user writes down such a type explicitly, a warning can be shown.

A warning could also be shown if such an "empty" type ends up as the type of a typed named element, e.g.:

```
var x = gb4.ctor;
```

The rationale for allowing such bogus ConstructorTypeRefs is similar to allowing empty intersections (fewer special cases in the internals of the type system).

Open question: how does this translate to ClassifierTypeRefs?

**Comment by yoosiba** [comment]
@mor-n4 can we close this? should we move it to eclipse/n4js ?

**Comment by mor-n4** [comment]
moved text to IDE-2320.
Closing this as duplicate.
