### ISSUE TITLE
Provide way for lightweight @StringBased enums

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#23]
IDEBUG-319
 For simple sets of enums, an explicit module generated is redundant, but all usages of the enum could simply be replaced with their corresponding enum value. 

E.g. a proposal would be that with

```
@@ProvidedByRuntime

/**
 * https://tools.ietf.org/html/rfc2616#section-5.1.1
 */
export @StringBased external public enum Method {
    OPTIONS,
    GET,
    HEAD,
    POST,
    PUT,
    DELETE,
    TRACE,
    CONNECT
}
```

any usage of Method.POST would simply be replaced in the transpiled output with "POST".

**Comment by mor-n4** [comment]
this has been implemented in Feb 2016 as part of another task
-> closing this now
