### ISSUE TITLE
Improvement: Remove optional modifier when inferring type

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#232]
The following variable declaration of `d` infers as an optional type, although there's a given non-optional fallback:

``` js
function foo(v: int?) {
    let d = v || 5; // d is of type `int?`
}
```

This is sometimes inconvenient w.r.t. spec initializers which require non-optional arguments.

**Comment by mor-n4** [comment]
requires clean-up of handling of optional type modifier in general:
- for fpars syntax has to change anyway (use ES6 default initializers)
- there are differences in semantics between optional fpar, optional return type, optional field
- clarify relation to null-analysis

**Comment by mor-n4** [comment]
I have just created a user story for the overall clean-up of type modifier handling: IDE-2405

**Comment by mmews-n4** [comment]
IDE-145 solves this regarding formal parameters (by removing this type modifier). IDE-2405 deals with the other occurrences of the optional type modifier '?'.

**Comment by yoosiba** [comment]
fixed in eclipse/n4js
