### ISSUE TITLE
Validation error in the context of iterator issuing wrong 'All N4Objects must explicitly extend/implement definition site structural type Iterable<?>.' message

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#236]
This disallows to implement the iterator protocol in nominal n4js types for `for-of` loops.

Apparently an error in for-of validation:

```

class D implements Iterator<int> {
    @Override
    public next(): IteratorEntry<int> {
        return null;
    }
}

function forOf2(i: Iterator<int>) {}

var d = new D();
// XPECT FIXME noerrors --> "All N4Objects must explicitly extend/implement definition site structural type Iterable<?>." at "d"
for(var x of d) {}
// XPECT noerrors -->
forOf2(d);
```

**Comment by mor-n4** [comment]
after some investigation and discussion with Daniel:
- the expected type of the expression following the "of" in a for..of loop is definitely `Iterable<?>`, not  `union{Iterable<?>,Iterator<?>}`, so our current implementation was correct.
  
  For details, see
  http://www.ecma-international.org/ecma-262/6.0/index.html#sec-runtime-semantics-forin-div-ofheadevaluation-tdznames-expr-iterationkind
  http://www.ecma-international.org/ecma-262/6.0/index.html#sec-getiterator
- the `IteratorExt` in stdlib implemented `Iterable` only structurally, not nominally, so the "All N4Objects must explicitly extend/implement ..." error message was actually correct
- as a solution, we decided to let interface `IteratorExt` extend built-in interface `Iterable` _explicitly_ (i.e. nominally).

(an alternative would have been to "fake" a use-site structural type in the type expectation for the for..of loop)

Closing this ticket as fixed (though no changes in n4js repo).
