### ISSUE TITLE
Unexpected validation error on index access

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#238]
##### A.n4js.xt

```
class ~Foo {}

let obj: Foo+,
    str = "bar";

obj.bar; // OK
obj["bar"]; // OK
// XPECT noerrors --> "Indexed access is not allowed for class instances."
obj[str]; // not OK?

```

**Comment by mmews-n4** [comment]
As far as I understand the Lang-Spec correctly, the behavior above is in N4JS-mode correct, i.e. the error at that location is desired.

Lang-Spec 8.1.7 Constraint 93.1 "Index Access" says:

> A limited form of computed-name indexed-access is allowed in N4JS mode. This is limited in that the index must be a string literal, in other words, a compile time known constant [...].

Still, a compile time known constant should work here. But doesn't seem so. Have a look at the example below.

```
class Foo {
    @Final cx = "cx";   
    cobj: Foo;

    f () {      
        // XPECT FIXME noerrors
        this.cobj[cx]; // error here, but should be ok
    }
}

let obj: Foo+;
const x : string = "x";

obj["x"]; // OK

// XPECT FIXME noerrors
obj[x]; // error here, but should be ok
```

**Comment by mmews-n4** [comment]
At the moment, we can not compute the value of a const or @Final variable at compilation time. Thus, we adjust the Lang-Spec (8.1.7 Constrant "Index Access") to the current implementation: 

> Indexed-access [...] is limited in that the index must be a string literal.

**Comment by dbo** [comment]
What's the reasoning behind this limitation to string literals in the spec in this case?

**Comment by mmews-n4** [comment]
Regarding receivers of dynamic type it seems reasonable to allow indexed-accesses using expressions which cannot be computed during compile time. Consider the following example:

```
class Foo {}
function f() : string { return "zzz";}
let obj: Foo+;
var zzz = "zzz";

obj.zzz = "";
obj["zzz"];
obj[zzz]; // no error desired
obj[f()]; // no error desired
```
