### ISSUE TITLE
Error on project symlinked folders: noModuleWrap paths shouldn't match n4js files.

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#239]
I get a manifest validation error: "noModuleWrap paths shouldn't match n4js files."

```
...
Output: "src-gen"
Sources {
    external {
        "src/js"
    }
}

ModuleFilters {
    noModuleWrap {
        "**"
    }
}
```

Steps to reproduce:
1. Create a project with plain/ES5/external JS files.
2. Move the project or any parent folder.
3. Symlink `ln -s ...`.

**Comment by JensN4** [comment]
We need to review filters in general.
Besides: cf. IDE-2166 As a smith I must not use File.getCanonicalFile()
