### ISSUE TITLE
Add error if constructors is defined generic

### ISSUE THREAD

**Issue by kduske-n4** [NumberFour/n4js#240]
Currently it appears to be unclear whether constructors can have generic type parameters of their own or not. Consider the following example.

```
    class X {
        // XPECT FIXME error --> "Constructor cannot be defined generic.""
        public <T> constructor(x: T) {
            console.log(x);
        }
    }

    new X(7);
```

The instantiation `new X(7)` however has an error at `7`: _int is not a subtype of T._ It should be clarified whether constructors with generic type parameters are forbidden or not, and in the former case, there should be a validation for that, and in the latter case, they should be callable without error.

**Comment by JensN4** [comment]
Constructors cannot be generic. We have to add a validation. Changed title accordingly.

**Comment by JensN4** [comment]
Bug reserved for candidate! Please do not work on that at the moment!

**Comment by jpilgrim** [comment]
cf. https://github.com/eclipse/n4js/issues/158
