### ISSUE TITLE
Consistent handling of computed property names and index access (maybe with "static expressions")

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#241]
In computed property names and index access we should allow the same kinds of expressions. Also the internal implementation of these rules should be consistent (only a single implementation that is applied for both use cases) and the error messages should be consistent.

In addtion, this might be a good opportunity to introduce the concept of static expressions and then allow static expressions in computed property names and index access.

Overall, the current implementation behaves consistently, but should be cleaned up (avoid duplication of logic) and should maybe be based on static expressions. Here an example showing the misleading error message:

```
class A2 {
    // OK, here we get:
    // XPECT errors --> Unsupported feature: computed property/member name using an expression other than string literal or built-in symbol.
    [`sdfsdf `]:string = "sdf";
    [""]="asd";
}
var a2:A2;
// The following line gets an error with message "Indexed access is not allowed for class instances." But for consistency I would expect something like above:
// XPECT FIXME errors --> Unsupported feature: computed property/member name using an expression other than string literal or built-in symbol.
a2[`sdfsdf `];
a2[""].length; // OK, works and now makes me think about the message above ?!
```

**Comment by yoosiba** [comment]
@mor-n4 I think we can close this

**Comment by mor-n4** [comment]
yes, this should be all done when compile-time expressions were introduced.
Closing this now.
