### ISSUE TITLE
Composition Type equivalence doesn't meet expectation

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#244]
In case union and intersection types are mixed in one composition type, the resulting composition type can be re-formulated. Doing so one can declare two or more equivalent composition types with a different structure. But as of now, such two structure-different types which are supposed to be equivalent are recognized as different types by the N4JS-editor. The following example shows the error in the last line.

```
interface A {}
interface B {}
interface C {}

var z1 : A & (B | C)
var z2 : (A & B) | (A & C)

// works fine
// XPECT nowarnings --> 
z1 = z2; 

// Error message: "intersection{A,union{B,I}} is not 
//   a subtype of union{intersection{A,B},intersection{A,I}}."
// XPECT FIXME nowarnings --> 
z2 = z1;
```

**Comment by JensN4** [comment]
One thing is that we have not defined any associative rules. But even though it should work, seems as if there is problem in the existing subtyping rules...

**Comment by JensN4** [comment]
possible solution, see IDE-2301 (canonical representation of types)
If this bug requires a canonical representation of types, than IDE-2301 needs to be done as well.

**Comment by JensN4** [comment]
cf. #213 although I would say that it should not be necessary to  simplify intersection types in order to compare them.
