### ISSUE TITLE
Intersections types must not contain more than one class

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#245]
This is a follow-up issue of GH-13.
This issue realizes the type constraint 18.2 (Chapter 4.10.2: Intersection types) "Only one class must be contained in the intersection type" of the language specification.

At moment, only warnings are shown when an intersection type contains two or more unrelated types. This check is done on the type model and uses the simplifies method of the TypeSystemHelper class. 

The current check won't identify two or more unrelated types in cases of deeply nested composed types. To do so, a thorough analysis would be necessary like converting the composed type into its canonical form (see GH-244). Hence it might be reasonable to analyze the canonical form for solving this issue here.

Solving this issue here also involves the type constraint solver, since it can also calculate composition types that contain two or more unrelated classes. During this calculation, constraint 18.2 also has to hold and thus can influence the solution of the solver.

**Comment by mor-n4** [comment]
closing this; moved to a user story, see IDE-2302

**Comment by JensN4** [comment]
Issue is not done, is it? Re-opened issue, set label "enhancement".

**Comment by JensN4** [comment]
after discussion: closed this issue as duplicate
