### ISSUE TITLE
Formatter doesn't adapt Resource Markers

### ISSUE THREAD

**Issue by meysholdt** [NumberFour/n4js#246]
Since the formatter inserts / deletes whitespace etc. the offsets of all subsequent tokens in the same file change. Usually, resource markers are expected to be moved along to the new offsets. This is relevant for content-independent resource markers, e.g. bookmarks an breakpoints. It is less relevant for content-derived resource markers, e.g. validation errors, TODO-markers, etc, because those are automatically updated during the editors reconciliation phase.

Xtext by default achieves the described behavior by wrapping all formatting-text-changes as `ReplaceEdit` into a `MultiTextEdit`. Thus, the text editor has sufficient information at hand to adjust the resource markers offsets.

For n4js, however, applying a single replace edit is a time-expenive operation since [ParserBasedDocumentTokenSource](https://github.com/NumberFour/n4js/blob/master/plugins/eu.numberfour.n4js.ui/src/eu/numberfour/n4js/ui/editor/syntaxcoloring/ParserBasedDocumentTokenSource.java) does a full re-parse of the document after each replace operation. When formatting files with >1000 lines and a `MultiTextEdit` with >1000 `ReplaceEdits' is expected to be applied on the document, the operation takes several minutes.

Xtext by default uses [DocumentTokenSource](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/DocumentTokenSource.java) which only uses the Lexer (!) for the local (!) text region, i.e. the modified region incl. surrounding token regions.

As a workaround, there is `eu.numberfour.n4js.ui.formatting2.FixedContentFormatter` that merges all replace edits into a single replace edits, thus significantly speeding up the operation. However, the drawback of this solution is that offsets of resource markers are not updated.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/580
