### ISSUE TITLE
Allow functions as type variables. Also consider use-side structural types.

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#249]
The possibility to use functions as type variables for bounds seems to be broken. This affects arrow functions, too. Also, use-side structural types cannot be used, which should be reviewed.

```
// OK XPECT noerrors -->
class  A<Z extends Function> {s : string}

// OK XPECT FIXME noerrors -->
class  A<Z extends {function (T)}> {s : string}

// OK XPECT FIXME noerrors -->
class  A<Z extends () => string> {s : string}

class D {}
// OK XPECT FIXME noerrors -->
class  A<Z extends ~D> {s : string}
```

Note: search for GH-249 in matrix tests.

**Comment by JensN4** [comment]
This is not even supported by the parser at the moment.
But in general iut's a good idea. Probably related to type definitions, e.g.

`typedef callback = {function(T)}`

or something like that

**Comment by kduske-n4** [comment]
May already have been solved in the course of https://jira.numberfour.eu/browse/IDE-1579

**Comment by mmews-n4** [comment]
fixed
