### ISSUE TITLE
Revisit Promise signatures

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#25]
IDEBUG-342
 Currently Promise has some flaws, e.g.
```ts
public static all(iterable: Array<?>): Promise<Array<any>, any>
public static race(iterable: Array<?>): Promise<?, any>
```

should rather use an Iterable (see http://www.ecma-international.org/ecma-262/6.0/#sec-promise.all).

- Promise.all cannot cleanly resolve to some type, I suggest to change it to

```ts
public static <T> Promise<Array<T>, any> all(Array<union{Promise<T, ?>, T}> iterable)
```

- The error type F is rather inconvenient and is commonly set to any/? (e.g. @Async notation).
Recommendation is that the error type is always of type Error (see https://www.w3.org/2001/tag/doc/promises-guide#reasons-should-be-errors).
WebIDL doesn't type it at all (any, see https://heycam.github.io/webidl/#es-promise).

It is only about changing the signature, cf.  https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.all

**Comment by mor-n4** [comment]
@dbo Is this still required or can we close it?
(formatting is messed up above, so maybe better check the original ticket IDEBUG-342)
