### ISSUE TITLE
Formatter is moving case opening brace to new line in switch-case

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#251]
before formatting:

``` typescript
enum E{
    A,B,C
}
function f(e :E){
        switch (e) {
            case E.A: {
                console.log(e);
                break;
            }
            case E.B: {
                console.log(e)
                break;
            }
            case E.C: {
                console.log(e)
                break;
            }
            default: {
                throw new Error (`unsupported event type ${event.type}`);
            }
        }
}
```

after formatting:

``` typescript
enum E{
    A,B,C
}
function f(e :E){
        switch (e) {
            case E.A: 
               {
                console.log(e);
                break;
            }
            case E.B: 
               {
                console.log(e);
                break;
            }
            case E.C: 
               {
                console.log(e);
                break;
            }
            default: 
               {
                throw new Error (`unsupported event type ${event.type}`);
            }
        }
}
```

**Comment by mmews-n4** [comment]
Daniel also prefers to have the opening bracket of the block in the same line like the colon of the case clause. Reason: the code is more compact this way.

**Comment by kduske-n4** [comment]
You know who also likes that? This guy right here.

**Comment by mmews-n4** [comment]
**Brief summary**

_When is the first statement S of a case clause moved to the next line after the colon C of the case clause?_
- S is always moved to the next line if there are more than one statements in the case clause
- if there is only one statement in the case clause:
  - if S is a block, the start of S (i.e. the opening bracket) is always in the line of C
  - if S is not a block, S can be located either in the line of C or in the next line of C
