### ISSUE TITLE
Enhancement: Discuss/think of supporting native instance-of checks against interface types.

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#252]
Currently `instanceof` checks are transpiled into calls of `$instanceof` to support checking for implemented interfaces.
This means native ES6 callers could not check for interface types/objects using just `instanceof`.
We could support this by defining `Symbol.hasInstance` on the constructor, see [Symbol.hasInstance on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance).

**Comment by JensN4** [comment]
I know. When we introduced that feature, Symbol.hasInstance was not available. I label this issue as feature request with low prio, since we do not have "native ES6 callers" yet.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/579
