### ISSUE TITLE
Built-in example project generator creates outdated manifest.n4mf file.

### ISSUE THREAD

**Issue by torstenkraemer** [NumberFour/n4js#259]
The built-in generator for an example projects generates an old version of the "manifest.n4mf" file format. 
This file cannot be parsed and therefore the project is broken.

We should introduce a test case which validates the generated file / project.

Generated code:

```
ArtifactId: n4js.example.tasks
VendorId: eu.numberfour
ProjectName: "n4js.example.tasks"
```

must be replaced by 

```
ProjectId: n4js.example.tasks
VendorId: eu.numberfour
```

**Comment by mor-n4** [comment]
note: the other problem in the built-in example (tests cannot be run in node.js) will be fixed by GH-264.
