### ISSUE TITLE
no checks on primitive value property access

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#262]
There is no validation or type checks on primitive value property access:

``` typescript
let i :int = 1337;

let n: number;
let s: string;

//FIXME "can't access property of the primitive"
n = i.x;
//or at least
//FIXME "any is not subtype of 'string'"
s = i.x;
```

**Comment by yoosiba** [comment]
also see _Don't allow passing primitive types as spec object and for structural types in general_ #4

**Comment by mor-n4** [comment]
seems to be a problem in the scoping; the fact that the type system infers `i.x` to an UnknownTypeRef (and thus allows assignment to any other type) is ok in this case, because this is the type system's way of saying "duh, there's an error here, but I am not responsible for reporting it"
