### ISSUE TITLE
Working sets based on git repos are not automatically refreshed

### ISSUE THREAD

**Issue by ghost** [NumberFour/n4js#267]
This is a somewhat convoluted issue. Here's what happened:

1) I installed the new product.
2) I used my **existing** workspace with it.
3) After that, the working sets based on git repositories were not displayed anymore (i.e. all the projects were filed under "Other projects"). Other working set types (i.e. based on project type) worked as expected.

The following measures helped to fix the problem:
- resetting the N4JS perspective (worked for the public version of the product)
- switching between different working set types, selecting and deselecting working sets in the "Configure Git Repository" menu (worked for the internal version for some developers)
- creating a new empty repository from the IDE's "Git Repositories" view (worked for the internal version for other developers)

**Comment by torstenkraemer** [comment]
Just learned from @alisa-lisovskaya , that this loss of working sets happens also after pulling an update from the nightly build via the update-site. 
Raised prio

**Comment by torstenkraemer** [comment]
The problem is caused by querying on a pre-initialized EGit RepositoryCache instance. Can be solved by adding a lazy init mechanism for our dynamic working-set implementation.
