### ISSUE TITLE
Cannot launch node if path to ide contains spaces

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#27]
IDEBUG-353
 Cannot launch node if path to ide contains spaces.

Reproduce:
- Extract product
- make sure path to product has no spaces
- simple console.log example should print something to console
- rename path to contain spaces
- restarting ide and running does not do anything

This is true for both, the node runner and the old node execution engine. The later prints at least an error message to console (saying that node is not found).

**Comment by torstenkraemer** [comment]
- checked on MacOS; works for white-space in folder names both of 
  - product and 
  - workspace.
- checked on Win10; works for white-space in folder names both of 
  - product and 
  - workspace.

Closing as already fixed.
