### ISSUE TITLE
Recursion not possible for a type argument of a generic class in a static polyfill

### ISSUE THREAD

**Issue by ghost** [NumberFour/n4js#274]
The description is a mouthful but here is an example.

The generated class:

``` typescript
@@StaticPolyfillAware
export public class AClass<T extends AnInterface<T>> extends BClass<T> { ... }
```

The static polyfill:

``` typescript
@StaticPolyfill
// XPECT FIXME noerrors -->
export public class AClass<T extends AnInterface<T>> extends AClass<T> { ... }`
```

There is an error at the `AClass<T>` saying: `T is not a subtype of AnInterface<T>.` Without recursion, no problem occurs (cf. [the static polyfill for Quantity](https://github.numberfour.eu/NumberFour/stdlib_api/blob/master/packages/eu.numberfour.stdlib.model.common.api/src/n4js/n4/model/common/Quantity.n4jsd#L17)).

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/578
