### ISSUE TITLE
Allow use and access to well-known symbols

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#282]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols

**Comment by JensN4** [comment]
@dbo Can you specify priority for that? Are some symbols more required than others?

We will probably create a user story for that. We then have to implement a way to define these symbols in the runtime. So I assume this will require a little bit more work...

**Comment by dbo** [comment]
Not of higher priority regarding current projects.

**Comment by yoosiba** [comment]
cannot reproduce in https://github.com/eclipse/n4js

**Comment by dbo** [comment]
@yoosiba: `Symbol.species`, `Symbol.toPrimitive`, ... in fact there are some very interesting ones.

**Comment by yoosiba** [comment]
@dbo ah, I have misread the list of `Symbol` properties. 
Created issue in eclipse/n4js, this stays closed (no development is done in this repo anymore).
