### ISSUE TITLE
Support async iteration

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#283]
Since the async iteration proposal is already at stage3 (candidate) including decent babel plugin support, I propose to support it in N4JS, too, enabling good async API design.

The feature actually comprises two features (which might be split):
- `for` - `await` - `of` loops
- async generators

Proposal: https://github.com/tc39/proposal-async-iteration
rauschma: http://www.2ality.com/2016/10/asynchronous-iteration.html

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/572
