### ISSUE TITLE
Using name of declared functions as type is allowed (probably unintentionally) but does not work properly

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#285]
```
function foo(n:any) {}
let f: foo;
let f2: Function = f; // shows error: "foo is not a subtype of Function." at "f"
```
The problem is that the parser creates a ParameterizedTypeRef for the type of `f` but according to our types model it should be a `FunctionTypeRef` if the declared type is a TFunction. This inconsistency later leads to problems in the subtype rules in Xsemantics.

However, the parser cannot know which kind of TypeRef to choose, so this either needs complex special handling, a major refactoring of our types model (get rid of FunctionTypeRef and always use ParameterizedTypeRef instead), or it has to be disallowed altogether (i.e. show error at "foo" in line `let f: foo;`, above).

**Comment by yoosiba** [comment]
IMHO disallowing will impose strong restriction over how one can use (N4)JS.
Aloso, note that we have other issues which demand more love for function types on our side ( #210 #204 #227 #249 ). I assume there will be some overlaps in _special handling_ / _major refactoring of our types model_ to solve those issues, so dismissing this use case does not help much.

**Comment by mor-n4** [comment]
thanks for the link! I was looking for #204 but couldn't find it.

Maybe `let f: foo;` (with `foo` being a declared function) would be nice to have (I thought it's not needed, but looking at #204 it seems we wanted to support it). All I'm saying is it won't be trivial to implement and we should get rid asap of the current situation of not showing an error for code we do not properly support.

**Comment by mor-n4** [comment]
closing this as duplicate of #204

**Comment by mor-n4** [comment]
reopened: will implement a validation to disallow for now under this ticket
#204 can then be used to add proper support and remove the temporary validation
