### ISSUE TITLE
create warnings for unused declarations

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#286]
We should have warnings for unused declarations (functions, classes, interfaces) the same way as we have them for unused variables.
```typescript
//XPECT issues --- "The value of the local variable v is not used"
let v;//correct warning

//XPECT FIXME issues --- "Local function f is not used"
function f(){}//no warning!!

//XPECT FIXME issues --- "Local class C is not used"
class C{}//no warning!!

//XPECT FIXME issues --- "Local interface I is not used"
interface I{}//no warning!!
```

declarations  on script level should have this only if not exported.

**Comment by JensN4** [comment]
I agree. I think we should also add a `@SupressWarnings("unsused")` -- just for this (and the variable) warnings. It simply is too annoying in tests etc.
