### ISSUE TITLE
As a developer I need support for ES6 tagged template functions

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#289]
https://tc39.github.io/ecma262/#sec-tagged-templates

**Comment by JensN4** [comment]
```
var a = 5;
var b = 10;

function tag(strings, ...values) {
  console.log(strings[0]); // "Hello "
  console.log(strings[1]); // " world "
  console.log(strings[2]); // ""
  console.log(values[0]);  // 15
  console.log(values[1]);  // 50

  return "Bazinga!";
}

tag`Hello ${ a + b } world ${ a * b }`;
// "Bazinga!"
```
Example taken from https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals

We will create a user story for that.

**Comment by JensN4** [comment]
Created user story.

@dbo Please tell me the priority of this feature request.

**Comment by dbo** [comment]
Raising priority, since usage is quite common across well known libraries.

**Comment by yoosiba** [comment]
see https://github.com/eclipse/n4js/issues/24
