### ISSUE TITLE
Show compile-time error for Temporal Dead Zone

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#290]
We should show compilation error for accessing TDZ, otherwise code will throw ReferenceError at runtime.
```typescript
class A{
	public f(){}
}

function fn(){
	//XPECT FIXME errors --> "Accessing uninitialized reference" at "a.f"
	a.f();
	let a:A = new A();
}
```

relevant part of the generated code:
```typescript
//...
	'use strict';
//...
		var A, fn;
		A = function A() {};
		fn = function fn() {
			a.f();
			let a = new A();
		};
//...
```

**Comment by yoosiba** [comment]
Thinking about this I propose to change this to bug. It is actual problem that we miss and produce code that throws exceptions at runtime. This is big no-no.

**Comment by mor-n4** [comment]
Showing a compile-time error for this would be tricky, because whether the exception occurs at runtime depends on the actual control flow. For example:
```javascript
// ES6 code

function foo(max) {

	for(let i=1;i<=max;i++) {
		if(i>10) {
			console.log(n);
		}
		let n = i;
		console.log(n);
	}

}

foo(5); // works fine
foo(15); // will throw exception
```
Also consider closures:
```javascript
// ES6 code
let fnBAD = () => console.log(n);

function bar() {

	let fnGOOD = () => console.log(n);

	let n = 42;

	fnGOOD(); // all "good"
	fnBAD(); // breaks
}

bar();
```
We could, however, consider a warning.

In any case, I'd propse to change this to a user story.

**Comment by yoosiba** [comment]
cannot reproduce in https://github.com/eclipse/n4js
