### ISSUE TITLE
Add persisted npm handling log

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#306]
Managing npm dependencies (i.e. installing) might result in exceptions of various nature (IDE not handling package.json properly, broken npm packages, etc.).
When these things happen natural reaction of the user is to retry their actions, or try to workaround them. As a result bugs reported are often follow up bugs that stand from multiple things done, hiding original action and original bug.

Add persisted external libraries log for better communication. It will help with understanding what were the steps that resulted in the bug, and what were workarounds that resulted in follow up errors.

**Comment by yoosiba** [comment]
with new maintenance actions in Library Manager it is much easier to manage state of external libraries. Lowering priority.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/571
