### ISSUE TITLE
Add npm test for npm packages integration independed from npm itself

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#307]
For testing adaptation of npm packages to the N4JS project model we use integration test that depends on 
* spawning git process that will clone definitions repository
* spawning npm process that will fetch npms over the network and install them in the local filesystem
* spawnig whole compiler to compile projects
* spawning nodejs process to run compiled code.

That approach is ok to assure support for *some* crucial npms, but is overhead for assuring npm adaptation works correctly.

Refactor current state:
* one integration test that assures crucial npms are handled correctly
* small unit tests for various parts of handling npms (preferably use static test assets instead of external processed and network connections).

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/570
