### ISSUE TITLE
New xpect version changed API, introduced compilation error in IDE

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#309]
My current Oomph based ide installation uses ```org.xpect.ui``` bundle in version ```0.1.0.201609091551```.

Performing new Oomph install pulls version ```0.2.0.201611170958```. That causes compilation problems of the IDE.

--edit
see https://github.com/meysholdt/Xpect/issues/203

**Comment by torstenkraemer** [comment]
Strategy here would be 
- pinpoint `org.xpect.ui` in one Manifest at least to `< 0.2.0` version 
- or -
- solve the compilation problem and submit patch to master

**Comment by yoosiba** [comment]
Code wise patch is simple, literally two liner, but I don't know if there won't be issues at runtime. I will run builds with the patch.

@meysholdt are there any changes to the behaviour that are risky ?

**Comment by meysholdt** [comment]
@yoosiba thanks for trying the new version! I'll comment on your code changes :)

**Comment by torstenkraemer** [comment]
Just created a ticket, that describes the underlying cause  https://github.com/meysholdt/Xpect/issues/203

**Comment by yoosiba** [comment]
With changes in Xpect and in N4JS (recent update of target platform) this issue is gone.
Closing.
Thx @meysholdt and @torstenkraemer for changes in last weeks.
