### ISSUE TITLE
n4jsc.jar uses incorrect ProjectId for compiled output

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#310]
When using the `n4jsc.jar` for individual projects (folders), the `manifest.n4mf`s `ProjectId` is not reflected in the output tree as (`Output`/es/`ProjectId`), but the directory's folder name instead is used.

**Comment by kduske-n4** [comment]
This is actually intended behaviour. When asked for its ID, projects [return the name of the containing folder](https://github.numberfour.eu/NumberFour/n4js/blob/master/plugins/eu.numberfour.n4js/src/eu/numberfour/n4js/internal/N4JSProject.java#L208). The comment also mentions that there is supposed to be a validation that ensures that the project ID always matches the containing folder name. It appears that got lost.

I will reinstate the validation, so I'm afraid you will have to either relocate your project or change its ID to match the containing folder name. Furthermore, we should discuss whether we should remove the project ID from the manifest altogether if it always matches the containing folder name anyway. 

@torstenkraemer @mor-n4 @JensN4 @yoosiba your input would be welcome.

**Comment by yoosiba** [comment]
1. remove ```ProjectID```
2. align validation with ```NPM``` requirements for package name
3. ensure ```NewProject``` wizard is aligned
4. consider ```NFAR``` case (i.e. is manifest in folder in ```NFAR``` or directly in it?)

**Comment by dbo** [comment]
@kduske-n4 Despite the current behaviour I think `ProjectID` makes sense, similar to the NPM's package id (which is the package.json's name property, not the containing directory). AFAIK if you npm link an NPM package by folder, the package.json's name is used, *not* the directory/repo name.

In addition the comment "because the projectId must be available even if the project does not exist" reads strange to me. I'd say "no manifest, no project", so what's the deal here ;-) ?

**Comment by kduske-n4** [comment]
I don't know, the comment was added by @mor-n4, so let's see what he says.

**Comment by kduske-n4** [comment]
Ok, so the validation works, I get

> The projectId "IntersectionTypes2" defined in N4 manifest doesn't match project folder name "IntersectionTypes" used in file system.

@dbo  How did you create this project in the first place? Do you get this error as well?

**Comment by kduske-n4** [comment]
Also:

> Despite the current behaviour I think ProjectID makes sense, similar to the NPM's package id (which is the package.json's name property, not the containing directory).

If the project ID must be identical to the folder name, as it apparently does, then it does not make sense to have this redundancy, regardless of how NPM does things.

Maybe the requirement that the project ID must be identical to the folder name is bogus, but we'd have to hear from @mor-n4 first.

**Comment by dbo** [comment]
@kduske-n4 I didn't get that validation error, but noticed the problem when using the jar file. Yes, i used that structure on purpose to manage just one NPM layer as part of the Eclipse project. In general I consider the limitation to match the folder name as quite odd, also with regards to NPM projects. Why can't we follow the current IDE behaviour, i.e. use the defined`ProjectID` tof the project manifest; seems straight forward to me. I'd consider it a bug if a project manifest doesn't have a project ID, since the transpiled import statements refer to these. I'd prefer to completely decouple from folder or Eclipse project name (.project) and use the manifest.n4mf.

**Comment by kduske-n4** [comment]
@dbo 

* It's possible that n4mf is not validated in headless case. If that is the case, then it's [a separate bug](https://github.com/NumberFour/n4js/issues/337).
* Let us discuss the project structure on Monday when you can show me in the IDE.
* Then we can also try to determine why you don't see this error in the IDE also.
* Regarding the current IDE behaviour: The IDE behaves like the headless compiler in that it determines the target location of generated files using the project ID, and for the project ID, it gets the folder name.
* Everything else hinges on whether or not we can get rid of the requirement that project ID and folder name have to match.
* If the requirement is necessary, we can get rid of the project ID in the manifest. If the requirement is not necessary, then we should lift it and the transpiler should generate into the correct output folder.
