### ISSUE TITLE
A class exported as `default` doesn't get listed in the type browser

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#311]
If I export a class as the `default of a module, e.g.

```n4js
export default public class Foo {}
```
it doesn't get listed in the type browser (i.e. `CMD+SHIFT+T` on OSX).

**Comment by mmews-n4** [comment]
It seems that this bug is also related to XText bug discovered in GH-325: When removing the Yield parameter, the bug behaviour described here does not occur anymore.

**Comment by yoosiba** [comment]
https://github.com/eclipse/n4js/issues/439
