### ISSUE TITLE
Source maps don't work using V8 inspector integration of node.js

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#312]
While N4JS source maps work in the browser with the known limitations (i.e. polyfills), using the new node.js V8 inspector integration with Chrome devtools (`--inspect`, since appr. 6.9) renders debugging to not be possible, no source code is shown at all.

**Comment by JensN4** [comment]
@dbo How important is this feature? (Please feel free to set priority label)

**Comment by dbo** [comment]
Should definitely be fixed, but not a blocker on current projects.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/569
