### ISSUE TITLE
missing type arguments for callable constructors

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#313]
Currently you can define callable constructors in n4jsd files like:
```typescript
export external public class CallableThing {
    (arg: number): any
}

// let foo = CallableThing(707);
```

But we need a way to have a parameterized callable constructor.

The two options discussed were:

Allow the callable constructor access to a class type argument

```typescript
export external public class CallableThing<T> {
    (arg: T): T 
}

// let foo: number = CallableThing<number>(707);
```

or allow a callable constructor with a type argument

```typescript
export external public class CallableThing {
    <T> (arg: T): T 
}

// let foo: number = <number>CallableThing(707);
```

Also, to be considered a third option of allow both

```typescript
export external public class CallableThing<S> {
    <T> (arg: S): T
}

// let foo: number = <number>CallableThing<string>("hello friend");
```

**Comment by JensN4** [comment]
The first version is already supported by the syntax and only requires some semantic changes (in the call)...

@arrowplum @dbo @chanakyabhardwajj @alisa-lisovskaya Which version do you prefer?

**Comment by arrowplum** [comment]
Would the second option allow for type inference? Since it allows the constructor to be treated as an exported function that would be consistent, but really for me any of them are fine as long as we can get the types in.

**Comment by dbo** [comment]
I tend towards the third most liberal option. We all know use cases are rather rare, but the current use-case for ES6 Proxy (first option) is not flexible enough.

**Comment by ghost** [comment]
I agree with dbo about the third option, since it seems the most flexible.

**Comment by yoosiba** [comment]
I am just wondering if this is about N4JSDs, if yes there is no calls to adjust ?
If we are planning to allow callable constructor in the, remember this is against ES6.
```javascript
    class Point {
        constructor(x, y) {
            this.x = x;
            this.y = y;
        }
        toString() {
            return '(' + this.x + ', ' + this.y + ')';
        }
    }
    > typeof Point
      'function'
    > Point()
       TypeError: Classes can’t be function-called
```
https://tc39.github.io/ecma262/#sec-ecmascript-function-objects-construct-argumentslist-newtarget
http://www.2ality.com/2015/02/es6-classes-final.html

P.S. If it counts, I would vote for version 3 (syntax like any function signature), but isn't the special thing about constructors that they don't have return type?

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/567
