### ISSUE TITLE
Add links to publicly available videos

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#316]
Add links to publicly available videos:

* EclipseCon Europe 2016: N4JS - Sound Static Type System For ECMAScript 2015 And More. Presented at EclipseCon Europe, November 2016, Ludgwigsburg, Germany. [Youtube (30 min, Eclipse Channel)](https://youtu.be/6yhTZ4v96ts), [Session Details](https://www.eclipsecon.org/europe2016/session/n4js-sound-static-type-system-ecmascript-2015-and-more) --  N4JS is an open-source super-set of ECMAScript and an IDE for N4JS and ECMAScript, providing a sound type system.
* XtextCon 2014: How we built a typed JavaScript language and IDE (Case Study). Presented at [XtextCon](http://xtextcon.org) 2014, May 2014, Kiel, Germany. [vimeo.com (25 min, XtextCon Channel)](http://vimeo.com/channels/xtextcon/98446435) -- This talk is focused on type systems in the context of an Xtext based language
* EclipseCon Europe 2013: Beyond the box: How we built a JavaScript IDE with Xtext. Presented at EclipseCon Europe, October 2013, Ludgwigsburg, Germany. [Youtube (30 min, Eclipse Channel)](http://youtu.be/Xm-7aE1UMGY)  -- This talk is focused on tweaking the parser generated by Xtext

Probably add these links to the documentation overview (http://numberfour.github.io/n4js/userguides/index.html). The first one is a real "user documentation" related video, the other two are for developers.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/564
