### ISSUE TITLE
If superclasses do not implement custom constructors super() should not need to be called.

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#317]
```js
class SuperA{
//no constructor defined so defaults to 
//  public constructor(){}
}

class SubA extends A{
    //Error Must explicitly invoke constructor of super class SuperA.
    public constructor(aThing){
        console.log(aThing);   
    }
}
```

**Comment by JensN4** [comment]
This is an ECMAScript 2015 constraint. You always need to call the super constructor, this is mandatory!

cf. babel: 
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-1&experimental=true&loose=false&spec=false&code=class%20A%7B%7D%0Aclass%20B%20extends%20A%20%7B%0A%20%20constructor()%20%7B%7D%0A%7D
