### ISSUE TITLE
Multiple runtime libraries used by n4js have diverged from actual runtime libraries

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#318]
## Multiple runtime libraries used by n4js have diverged from actual runtime libraries 

some fixes (at least #71) that are tested and working for the `N4JS` ide are not working when used in application code.

**Comment by mor-n4** [comment]
I have just resolved some of the inconsistencies in the bootstrap code, as a quick fix.

However, the main problem is IDE-1571 and we should fix that asap.
