### ISSUE TITLE
Need to be able to type function signatures and typedef type expressions

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#319]
Consider writing an n4jsd for a  library with these signatures:

```js
export default external public class FetchMock{
    public static mock( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static once( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static get( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static put( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static post( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static delete( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static head( matcher:union{string, RegExp, {function(string, Object): boolean }},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
    public static getOnce( matcher:union{string, RegExp, {function(string, Object): boolean }},
                            response:union{Response,number, string, union{ResponseObject, Object}}, 
                            options: MockOptions?): this
    public static putOnce( matcher:union{string, RegExp, {function(string, Object): boolean }},
                            response:union{Response,number, string, union{ResponseObject, Object}}, 
                            options: MockOptions?): this
    public static postOnce( matcher:union{string, RegExp, {function(string, Object): boolean }},
                            response:union{Response,number, string, union{ResponseObject, Object}}, 
                            options: MockOptions?): this
    public static deleteOnce(matcher:union{string, RegExp, {function(string, Object): boolean }},
                            response:union{Response,number, string, union{ResponseObject, Object}}, 
                            options: MockOptions?): this
    public static headOnce( matcher:union{string, RegExp, {function(string, Object): boolean }},
                            response:union{Response,number, string, union{ResponseObject, Object}}, 
                            options: MockOptions?): this
``` 

These static methods are aliases of each other. in addition the matcher union as well as response are used for nearly every method in the library.

If we could typedef the unions and define the signature for the aliases it would make it all much clearer and when the apis change would reduce the amount of potential errors updating the n4jsd.

**Comment by JensN4** [comment]
@arrowplum  Could you provide a proposal?

**Comment by arrowplum** [comment]
@JensN4 since this is again a real issue with some readability I am looking back at this. Especially an issue is not being able to define a type alias for a function type.

haskel, scala, and typescript do type aliasing similarly using the `type` keyword. Something like:

```typescript
class Dog<TPaws, TColor, TBarkstyle, TBreed>{}
class Cat<TPaws, TColor, TPurrstyle>

type AnyAnimal = union{Cat<Paws.Declawed, Color.Black, LoudPurr>, 
    Dog<Paws.Normal, Color.Brindle, QuietBark, Breeds.Mutt>};
```

That is obviously not quite a good example of where it is needed, but just to show what  that syntax is. Adding function types would be similar. To use a real example, `dispatch` from redux is defined as:
```typescript
dispatch(action: union{Promise<ReduxAction, any>, ReduxAction}): 
    union{Promise<ReduxAction, any>, ReduxAction}
```
so a (simple) method that takes a dispatch function as a callback is something like:

```typescript
public doADispatch(dispatcher: {function(union{Promise<ReduxAction, any>, ReduxAction}):
     union{Promise<ReduxAction, any>, ReduxAction}})) {}
```

With type aliasing you would still have to define the signature somewhere but using it would be clearer.

```typescript
type DispatchFunction = {function(union{Promise<ReduxAction, any>, ReduxAction}): 
    union{Promise<ReduxAction, any>, ReduxAction}};
```

then that simple method would look like:

```typescript
public doADispatch(dispatcher:DispatchFunction){}
```

**Comment by arrowplum** [comment]
haskell: https://en.wikibooks.org/wiki/Yet_Another_Haskell_Tutorial/Type_advanced#Type_Synonyms

typescript: http://stackoverflow.com/a/28343437/4875054

scala: https://www.safaribooksonline.com/library/view/learning-scala/9781449368814/ch10.html#_type_aliases

scala type aliasing best practices(horrible link that doesnt parse and you have to cut and paste): 
`http://twitter.github.io/effectivescala/#Types and Generics-Type aliases`

**Comment by arrowplum** [comment]
@mor-n4

**Comment by mor-n4** [comment]
I think there are two topics:

1. When having a declared function or method, we could allow to use its name as a type, cf. example below. For some time, this was allowed, but it had to be disallowed because there were problems and it was not clear wether it is really desirable. Maybe we already have a task for this.
        iirc the problems weren't critical, but would need some work to get resolved (had to do with the parser and TypeRefs in the AST; parser would have to make the distinction between a ParameterizedTypeRef and a FunctionTypeRef, which it can't).

2. typedef / type aliases: this would definitely be a useful feature. However, I'm unsure how much effort it might be. To me, at first sight, it seems straightforward, but it might break some (implicit) assumptions we have made in the code in some places. Has to be seen. In any case, we should have a user story for this, instead of a GH ticket.

---

Example for 1)
```javascript
function foo(p: string): number {return 0;}
let f: foo;
```

**Comment by arrowplum** [comment]
It would be better if we could have function types without having to
declare a function. For example in defining an interface or n4jsd file.

**Comment by yoosiba** [comment]
For function signatures maybe interface with annotation? e.g.
```typescript
@FunctionalInterface
interface MatcherFn{
  public run(string, Object): boolean;
}

export default external public class FetchMock{
    public static mock( matcher:union{string, RegExp, ~MatcherFn},
                        response:union{Response,number, string, union{ResponseObject, Object}}, 
                        options: MockOptions?): this
}

//somewhere in impl
function myMatcher(string, Object): boolean {return true}
FetchMock. mock(myMatcher, 'res');
```
There will be some details to iron out (function declaration vs function expression, function properties, subtyping), but they will come up with every proposal.

**Comment by yoosiba** [comment]
as for type aliases:
 * proposal for Kotlin https://github.com/Kotlin/KEEP/blob/master/proposals/type-aliases.md
 * Haxe abstract type http://haxe.org/manual/types-abstract.html

**Comment by arrowplum** [comment]
Regarding https://github.com/NumberFour/n4js/issues/319#issuecomment-274494664 i would much prefer a plain `type MatcherFn = {function(string, Object):boolean}`  statement rather than defining an interface with a special annotation.

**Comment by mmews-n4** [comment]
related to https://github.com/NumberFour/n4js/issues/210

**Comment by arrowplum** [comment]
@kduske-n4 Here is the original issue
