### ISSUE TITLE
Missing validation for violation of constness in final-expression of for statement.

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#320]
In a `for` statement, If a const variable is defined in the first expression, and that variable is modified in the final expression it should receive a const violation error. The error occurs at runtime but is missing at compile time.
```js
        for(const foo = 9;;foo = 3);
```

**Comment by mmews-n4** [comment]
PR: https://github.numberfour.eu/NumberFour/n4js/pull/282
