### ISSUE TITLE
plain arrays not inferred correctly if union includes an array and an implementer of Iterable2

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#321]
```js
abstract class IterableThing<K,V> implements Iterable2<K,V>{
    
}
function foo (arg: union{Array<any>, IterableThing<any, any>}){}

foo(['hi', 'guy']); //Gets error Iterable2<any,any> is not a subtype of union{Array<any>,IterableThing<any,any>}.
```

**Comment by arrowplum** [comment]
attn @mor-n4

**Comment by mor-n4** [comment]
odd.

hint for further investigation:

start with the following two simplified examples, which do not involve `IterableN` but still fail. Problem is that `expectedElemTypeRefs` in `PolyProcessor_ArrayLiteral#processArrayLiteral()` is erroneously empty and thus the method goes into the performance tweak (which it should not).
```
function foo2(arg: union{Array<any>, Number}) {}
foo2(['hi', 'guy']); // error: Array<string> is not a subtype of union{Array<any>,Number}.

class C {}
function foo3(arg: union{Array<any>, C}) {}
foo3(['hi', 'guy']); // error: Array<string> is not a subtype of union{Array<any>,C}.
```
This won't fix the main problem from the task description, but it could help.

The main problem could have something to do with the known limitations that come from our decision to avoid backtracking in the constraint solver (for now). If so, this example should be added to IDE-2140.

**Comment by yoosiba** [comment]
see https://github.com/eclipse/n4js/issues/495
