### ISSUE TITLE
[n4jsc.jar] n4jsx resource files are not picked up for compilation

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#322]
In a project where n4js and n4jsx files are combined, n4jsx resources are not picked up properly:

`WARN:  Skipped file: could not create resource for URI=file:...`

**Comment by dbo** [comment]
[Foo.zip](https://github.com/NumberFour/n4js/files/670593/Foo.zip)

**Comment by mor-n4** [comment]
A quick fix has been applied but some DI-related problems remain (that also apply to the IDE case, not just the headless case). They will be further investigated as part of IDE-2493.
