### ISSUE TITLE
The type of methods of object literals should be displayed

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#323]
In the last line of the following code snippet, the hover label `variable o2g: [unknown]` is currently displayed, instead of showing the correct information about the method `g`.

```
let o2 = {
    string g() {}
};
let o2g = o2.g;
// XPECT FIXME type of 'o2g' --> {method * g1(): Generator<undefined,undefined,any>}
o2g;
```

**Comment by mor-n4** [comment]
Fixed during review of IDE-2488 (will be merged together with IDE-2488).
