### ISSUE TITLE
Tests with the extension ".n4jsx" do not run on Jenkins (but do run locally)

### ISSUE THREAD

**Issue by ghost** [NumberFour/n4js#327]
On Jenkins, only tests with ".n4js" extension are executed.
Locally, both ".n4js" and ".n4jsx" tests are executed.

**Comment by qtran-n4** [comment]
@alisa-lisovskaya I am currently investigating this issue.

**Comment by qtran-n4** [comment]
This is fixed with the following PR:
https://github.numberfour.eu/NumberFour/n4js/pull/278
