### ISSUE TITLE
n4jsx files automatically inserting closing bracket if content is below

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#329]
This should error: 
```typescript
const thing = [ 
    <div {...{}}/> 
const foo = '';
```

instead it produces: 
```typescript
				thing = [
					React.createElement('div', Object.assign({}, {}))
				];
				foo = '';
```

**Comment by arrowplum** [comment]
Related: If you hit enter constructing a fragment of jsx that is in an array it tries to insert a closing bracket in the middle. See this gif:

**Comment by arrowplum** [comment]
![bug2](https://cloud.githubusercontent.com/assets/417616/22020931/0036a526-dcbb-11e6-905e-6ffda82a6fa1.gif)

**Comment by yoosiba** [comment]
https://github.com/eclipse/n4js/issues/494
