### ISSUE TITLE
Wrong dependency on API project in generated code for N4JSX

### ISSUE THREAD

**Issue by qtran-n4** [NumberFour/n4js#330]
Step 1: Create `React.api` project of project type `API` and add `react.n4jsd` to the source folder

Step 2: Create `React.impl` project of project type `library` and add a mock implementation `react.js `in the source folder. The `manifest.n4mf` defines `React.api` in the `implementedProjects`.

```
ImplementationId: myreactid
ImplementedProjects {
    React.api
}
```

Step 3: Create `ReactMockTest` project of type `application`, add a file say `m.n4jsx` to the source folder that uses `React.api`. Everything should be fine at this point.

Step 4: Create a project called `SomeProject.API` of type `API` and also add `react.n4jsd` to the source folder. 

Now have a look at the generated for `m.n4jsx`. SomeProject.API is declared as a dependency!

**Comment by yoosiba** [comment]
fixed with 12d26a6a9faa0b49374dcdc9852128900841db9f
