### ISSUE TITLE
please don't disable "mvn install" plugin by default

### ISSUE THREAD

**Issue by meysholdt** [NumberFour/n4js#331]
in 
https://github.com/NumberFour/n4js/blob/master/releng/eu.numberfour.n4js.parent/pom.xml#L260
the 'maven-install-plugin' is disabled with the consequence that if you run `mvn install`, no install happens and no error/warning is reported. 

I understand this is useful to absolutely prevent a CI build from using old artifacts.

However, for contributors that want to run the build locally to track down errors, this is problematic, because it makes it impossible to build individual artifacts, e.g. `mvn clean verify  -f plugins/eu.numberfour.n4js.ts`. Building an individual artifact requires that needed artifacts are already installed into the local repo.

Maybe its possible to tie disabling of 'maven-install-plugin' to a specific maven profile, so that it's not active by default - in case that doesn't defeat the whole point of disabling it.

**Comment by torstenkraemer** [comment]
Hi @meysholdt, I disagree. 
This project is a tycho build (OK, ~ 95%) and is not using any installed maven artifacts at all. It produces p2-artifact not maven artifacts. 
Due to the complexity of configuration a local rebuild of a single plugin is not possible, since tycho relies on a properly filled reactor. 

Did you try it?  - Please prove me wrong with a PR that is actually working as you described here.

We disabled the install at all since we did run into the mvn-install hack in the past: Developers changed the build system unaware of installed artifact leading to a system that could never be bootstrapped. You did need at least one failing "install" build to prepopulate your local .m2 cache in order to get a green build in the second round. This was inacceptable. 

Cheers, Torsten.K

**Comment by meysholdt** [comment]
Hi Torsten,

I tried and after running `mvn clean install` I can successfully run `mvn clean install -f plugins/eu.numberfour.n4js.runner`.  The log output contains 

```
[WARNING] The following locally built units have been used to resolve project dependencies:
[WARNING]   eu.numberfour.n4js.n4mf/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.releng.utils/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.external.libraries/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.ts/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.utils/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.generator.common/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.n4mf.model/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.regex/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.ts.model/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.model/0.0.1.201701281914
[WARNING]   eu.numberfour.n4js.common.unicode/0.0.1.201701281914
```
so the project-local upstream artifact are really being pulled in from the local maven repo. 

Unfortunately, running `mvn clean install -f plugins/eu.numberfour.n4js` and `mvn clean install -f plugins/eu.numberfour.n4js.model` did *not* succeed, because plugin dependencies to project-local artifacts could not be resolved :-(

Example:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building eu.numberfour.n4js.model 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
(...)
[ERROR] Failed to execute goal org.eclipse.xtext:xtext-maven-plugin:2.11.0.RC2:generate (xcore-generator) on project eu.numberfour.n4js.model: Execution xcore-generator of goal org.eclipse.xtext:xtext-maven-plugin:2.11.0.RC2:generate failed: Plugin org.eclipse.xtext:xtext-maven-plugin:2.11.0.RC2 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.xtext:xtext-maven-plugin:jar:2.11.0.RC2 -> eu.numberfour.n4js:eu.numberfour.n4js.releng.utils:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for eu.numberfour.n4js:eu.numberfour.n4js.releng.utils:jar:0.0.1-SNAPSHOT: Failure to find eu.numberfour.n4js:eu.numberfour.n4js.parent:pom:0.0.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype_snapshots has elapsed or updates are forced -> [Help 1]
```

Closing.

cheers,
  Moritz
