### ISSUE TITLE
Test expectations should not depend on time zone of execution environment

### ISSUE THREAD

**Issue by meysholdt** [NumberFour/n4js#335]
many of the tests from [eu.numberfour.n4js.expectmatrix.tests/xpect-tests/builtin_js/date/](https://github.com/NumberFour/n4js/blob/master/tests/eu.numberfour.n4js.expectmatrix.tests/xpect-tests/builtin_js/date/) use `new Date(year, month, day)` to create new test objects. I assume this date is defined to relative to the execution environments (e.g. CI server) time zone. 
Computing the actual test value involves converting the date to UTC. Thus, the actual test value becomes dependent on the time zone.

Example: [date_setUTCFullYear.n4js.xt](https://github.com/NumberFour/n4js/blob/master/tests/eu.numberfour.n4js.expectmatrix.tests/xpect-tests/builtin_js/date/date_setUTCFullYear.n4js.xt)

Maybe instead of `new Date(year, month, day)` [Date.UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC) can be used.

**Comment by meysholdt** [comment]
all problematic tests are 
```
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_setHours.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_toUTCString.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_setUTCFullYear.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_parse.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_toISOString.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_getUTCHours.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_valueOf.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_toJSON.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_setMonth.n4js.xt#output~0
eu.numberfour.n4js.expectmatrix.tests.N4JSExpectMatrixTest.xpect-tests/builtin_js/date/date_setUTCMonth.n4js.xt#output~0
```
see http://services.typefox.io/open-source/jenkins/job/tf-n4js-master/32/

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/562
