### ISSUE TITLE
Validate project manifest in headless compiler

### ISSUE THREAD

**Issue by kduske-n4** [NumberFour/n4js#337]
Currently, the headless compilers does not validate the manifest files. It should validate them before it starts actually compiling projects.

* Should all manifests be validated, or only those of the projects which the user explicitly requested to be compiled? In other words, should manifests of dependencies also be validated?
* Manifests should be validated before the actual compilation begins, that is, [during project registration with the file based workspace](https://github.com/NumberFour/n4js/blob/master/plugins/eu.numberfour.n4js.generator.headless/src/eu/numberfour/n4js/generator/headless/N4HeadlessCompiler.java#L492).

**Comment by yoosiba** [comment]
In IDE broken dependency prevents compilation of the project. In headless case it should be the same. So if I want to compile ProjectA but its dependency ProjectB is broken (error in manifest) or missing, then ProjectA should not be compiled.

**Comment by yoosiba** [comment]
Actually IDE validates manifest, but not against the folder, but against value in the ```.project``` file.
It is part of the baggage we inherit from Eclipse.
Currently we have many project descriptions:
 * ```.project``` file for Eclipse
 * ```package.json``` file for npm
 * ```manifest.n4js``` for N4JS

In practice N4JS project needs to have all three aligned to work correctly. 
Having them in inconsistent state and inconsistent calls on N4JS.ide/N4JS.jar results in bugs like #310.

**Comment by qtran-n4** [comment]
I am currently looking into this bug.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/561
