### ISSUE TITLE
Different type computed for different variant of lamda (arrow function), should be similar

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#34]
```
class A{}

// XPECT FIXME noerrors --> "Array<any> is not a subtype of Array<A>." at "[]"
const lambda = (): Array<A> => [];

// XPECT noerrors --> 
const lambda2 = (): Array<A> => { return []; }

// XPECT noerrors --> 
const fe = function():Array<A> { return []; }

// get rid of warnings
lambda();lambda2();fe();
```

Currently type-checking the body of a single-expression arrow function is the responsibility of N4JSLambdaValidator.checkArrowFunction()
That method considers subcases like async arrow function, void-type body where an optional return type is expected. And so on.
On the other hand, there's N4JSTypeVaidator.checkTypeMatchesExpectedType() which is the canonical place to perform that kind of check.
This ticket is about adding rules in n4js.xsemantics to fit the input expected by N4JSTypeVaidator.checkTypeMatchesExpectedType() to perform its job for single-expression arrow functions too (considering all subcases that N4JSLambdaValidator.checkArrowFunction() considers.

**Comment by yoosiba** [comment]
Why is this _low priority **enhancement**_ and not a bug? We have this bug for a long time (original IDE issues filed in June 2015). If we keep this labels it will never get fixed.

Adding test case:

``` typescript
class A{}

//XPECT noerrors --> "Array<any> is not a subtype of Array<A>." at "[]"
const lambda = ():Array<A> => [];

//no error for multiline
const lambda2 = ():Array<A> => {
    return [];
}
```

**Comment by mor-n4** [comment]
changed this from "enhancement" to "bug" because it is not just a nice-to-have, internal refactoring but leads to actual problems (as the example of @yoosiba shows)

**Comment by JensN4** [comment]
For the record: I updated the original error description and title. From the old title I thought it is just an internal refactoring, only your example, @yoosiba, showed me that it is in fact a bug. And, whau, Oliver fixed this rather quickly. Great work, guys!
