### ISSUE TITLE
Coloring parser takes too long

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#340]
eu.numberfour.n4jsx.ui.editor.syntaxcoloring.HighlightingParser  - Coloring parser took: 42

Problems supposedly relates to the JSX mode.

**Comment by JensN4** [comment]
It also happens in n4js files. I assume the new syntax may be responsible for that.
Besides, we should try the TypeScript sytnax. That is, instead of
```function fn4(a: string = ) { }```
use
```function fts(a?: string ) { }```

**Comment by yoosiba** [comment]
It is strange for product users to see that since there is a guard in ```HighlightingParser``` to log only in debug mode:
```java
		boolean debug = LOGGER.isDebugEnabled();
                //...
		} finally {
			if (debug) {
				assert stopwatch != null;
				long elapsed = stopwatch.stop().elapsed(TimeUnit.MILLISECONDS);
				if (elapsed > 5) {
					LOGGER.warn("Coloring parser took: " + elapsed);
				}
			}
		}
```

We should check if debug log is enabled in product, as this should not be.

**Comment by yoosiba** [comment]
Also note, that users experience this since Feb 8th, while optional parameters were enabled earlier.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/559
