### ISSUE TITLE
'Building Workspace'-Error when saving n4js-file

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#349]
To reproduce the error, create a n4js-file with the contents below and hit Save.

**Contents of n4js-file:**
```javascript
interface I {
    num = 5;
    fn = [ () => console.log(this.num) ]
}
class C implements I {}

(new C).fn[0]();
```

**Error message:**
> Errors occurred during the build.
> Errors running builder 'Xtext Project Builder' on project 'Tester'.
> all arrow functions must have an original AST node (i.e. not allowed to add arrow functions programmatically in a transformation)

**Comment by JensN4** [comment]
This is fixed with GH-348
