### ISSUE TITLE
Support automatic conversion from Array<T> to T... when calling super methods or constructor with variadic parameters

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#35]
IDEBUG-464
 The following code snippet has errors: {{Array<string> is not a subtype of string.}}
Would be great to support it just like in Java:

```
class A {
    constructor(string... p) { }
    foo(string... p) { }
}

class B extends A {
    constructor(number n, string... p) {
        // XPECT FIXME noerrors -->
        super(p);
    }
    @Override
    foo (string... p) {
        // XPECT FIXME noerrors -->
        super.foo(p);   
    }
}
```

Valid use case, however the type system is correct. The problem is that we would have to rewrite the handling of variadic arguments. When doing that, review ES6 if there are any changes wrt argument etc.

Note the following case: f(Array<?> a...) --> this would lead to an array of arrays...

**Comment by mor-n4** [comment]
This should not be implemented as in Java. ES6 has its spread operator for these use cases, so instead we should just add support for ES6's spread operator. There exists a user story for that: IDE-2253.

Closing this as WONT FIX.
