### ISSUE TITLE
Missing ability to define optional read only field

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#352]
Currently if we want a field to be read only we define a getter with no setter. We especially use this in defining interfaces.

What is currently missing is the ability to define an optional read only field.

```typescript
interface ~Thing{
    public get readonlyFoo():string; 
    public optionalFoo:string?;
    // how? (public get optionalReadOnlyFoo():string)?
}
```

Blocks https://jira.numberfour.eu/browse/OPR-574

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/554
