### ISSUE TITLE
Cyclic references between files can confuse editor dirty state handling AND incremental builder / Xtext index

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#360]
In case of cyclic references between a file `A` opened in an N4JS editor and some other file `B`, the editor might show outdated information for the remote file `B` in case an unsaved change in the editor (for file `A`) has an effect on the TModule information of file `B`. In such a case, the dirty state handling does not update the information obtained from the index for file `B` until the editor contents are saved. In addition, also the incremental builder and Xtext index can become inconsistent until file `A` is saved repeatedly.

Unfortunately, this is not only a problem of the dirty state handling because it also affects the incremental builder.

To reproduce, create a file `A.n4js`:
```javascript
import {B} from "B";

export class A {
	static fieldA = 'some string';
}

let str: string = B.fieldB;
```
and a file `B.n4js`:
```javascript
import {A} from "A";

export class B {
	static fieldB = A.fieldA;
}
```
Now perform a clean build and then

1. open file `A.n4js` in an N4JS editor (do not open file `B.n4js`).
2. change the string literal `'some string'` to a number literal `42` (without saving!!).
3. now, an error is expected in the editor in the last line of file `A.n4js` (because the type of `B.fieldB` has now changed from string to number) but this error is not shown (Problem 1: inconsistent dirty state in editor).
4. save editor contents (i.e. save file `A.n4js`).
5. now, the editor shows the correct state (i.e. the error mentioned in step 3 shows up) but note that the incremental builder does not show this error, i.e. no error shown in Eclipse Problems View (Problem 2: inconsistent builder / Xtext index state).
6. add an empty line to file `A.n4js` and save again.
7. now the error mentioned in step 4 shows up in the Eclipse Problems View as well.

**Comment by mor-n4** [comment]
The exact same behavior can be reproduced using cyclic references caused by compile-time expressions (note: this won't work until IDE-2468 will be merged to master).

File `A.n4js`:
```javascript
import {B} from "B";

export class A {
	const fieldA = 'someFieldName';
}

class Test {
	static [B.fieldB] = 0;
}

Test.someFieldName;
```
File `B.n4js`:
```javascript
import {A} from "A";

export class B {
	const fieldB = A.fieldA;
}
```
Instead of changing the string literal to a number literal, just change literal `'someFieldName'` to something like `'someFieldNameX'`. Aside from that, you can follow the steps 1-7 from the task description and get the same behavior.

**Comment by szarnekow** [comment]
see https://github.com/eclipse/n4js/issues/66

**Comment by jpilgrim** [comment]
Simple example w/o classes:

File A:
```javascript
import {y} from "x/B";
export public var x = "hello";
export public var z: string = y;
```

File B:
```javascript
import {x} from "x/A";
export public var y = x;
```

Similar to initial example, change type of x (to int) to reproduce.

This seems like a problem in the incremental builder.
Before saving a file, in dirty state, we accept these kind of glitches.
