### ISSUE TITLE
JSX spread operator doesn't mind order w.r.t. overlapping properties

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#372]
```jsx
<div {...{ foo: 5 }} foo={3} />
```
foo should result to 3, but actually the transpiled code adds the spread object to the end of the Object.assign statement:

```js
Object.assign({ foo: 3 }, { foo: 5 })
```

so foo will result in 5.

I suspect this was meant as an optimization, but it is only applicable in case there's no overlap of the sets of properties involved.

**Comment by yoosiba** [comment]
Maybe this was not optimization, but avoiding mutation of properties.
Consider more common scenario
```typescript
interface ~BigLabelProps extends React.ComponentProps {
    public p1: string
}

class BigLabel extends React.Component<BigLabelProps, Object> {
    @Override public render(): React.Element {
        return <div {...this.props} foo={3} />
    }
}
```
this is compiled as
```typescript
return React.createElement('div', Object.assign({foo: 3}, this.props));
```
If we change just change order than in render
```typescript
return React.createElement('div', Object.assign(this.props, {foo: 3}));
```
than `this.props` is mutated. Is that expected?

or should it be more like
```typescript
let tmpProps = Object.assign({}, this.props);
tmpProps = Object.assign(tmpProps, {foo: 3});
return React.createElement('div', tmpProps));
```
