### ISSUE TITLE
N4JSC.jar cannot compile n4js-runtime-n4

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#376]
https://www.npmjs.com/package/n4js-cli contains jar that cannot compile `n4js-runtime-n4`

```
@issue = ERROR:Unsupported feature: default initializers for formal parameters. (file:/C:/Users/me/Documents/GitHub/tstc/node_modules/n4js-runtime-n4/src/n4js/n4/Profiling.n4jsd line : 68 column : 56)
ERROR: cannot compile project n4js-runtime-n4 due to 1 errors.
  ERROR:Unsupported feature: default initializers for formal parameters. (file:/C:/Users/ereb/Documents/GitHub/tstc/node_modules/n4js-runtime-n4/src/n4js/n4/Profiling.n4jsd line : 68 column : 56)
eu.numberfour.n4js.hlc.N4jsc$ExitCodeException
        at eu.numberfour.n4js.hlc.N4jsc.compileAndExecute(N4jsc.java:834)
        at eu.numberfour.n4js.hlc.N4jsc.doMain(N4jsc.java:486)
        at eu.numberfour.n4js.hlc.N4jsc.main(N4jsc.java:329)
null exitcode: 2 (compilation did not succeed)
```

**Comment by yoosiba** [comment]
thoughts @dbo  ?

**Comment by dbo** [comment]
strange, looks fine to me:

` public timeStamp(title: string, justOrder: boolean=): void;`

**Comment by mor-n4** [comment]
is there an n4jsc.jar bundled in n4js-cli? is yes, it seems to be very old; just needs an update

**Comment by dbo** [comment]
Of course, I thought kuba is using the npm from nexus. Right, the external needs an update.

**Comment by yoosiba** [comment]
This is about public https://www.npmjs.com/package/n4js-cli 
It seems to be outdated in comparison to publicly available [n4jsc.jar](http://n4js.s3-website.eu-central-1.amazonaws.com/ide/n4jsc.jar) and N4JSIDE

It is pretty bed experience for the user when in IDE everything works, and then everything goes to hell when calling npm.

**Comment by dbo** [comment]
@yoosiba give me a notice when it's good to update it.

**Comment by yoosiba** [comment]
in 2-3 days we will get changes in regards of optional fields, then we should update.

Ideally, n4js-cli should be updated with every master update.

**Comment by dbo** [comment]
yes and no, we don't have a canary channel to publish

**Comment by yoosiba** [comment]
Neither does IDE but is published every night from master (assuming tests pass etc.).
If n4js-cli does not follow it is broken.
