### ISSUE TITLE
public website contains outdated info about platform requirements.

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#377]
Currently [N4JS downloads](https://numberfour.github.io/n4js/index.html#getting-started) says
`System Requirements: In any case, Java 8 is required to be installed on your system. Node.js is also required in version 5+. The N4JS plugins require the Eclipse Mars release (4.5.1).`

This is outdated. We say node 6  and Eclipse Neon.2 (4.6.2)

**Comment by mmews-n4** [comment]
This is fixed in the temporary repo for the Eclipse website in spe: 
commit https://github.numberfour.eu/mmews/eclipsewww/commit/8b54ee7f29921da517ade842fbbb14cf8387eed4
