### ISSUE TITLE
N4JS example wizard does not properly generate the Tasks Example

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#381]
To reproduce:
1. download the N4JS IDE.
2. launch it and create a new, empty workspace.
3. right-click in explorer view and choose `New > Example ...` and select the N4JS example.

The code will be created in the workspace but will be wrong (wrong folder structure).

When fixing this, check why the test for the example does not fail, even though example generation is obviously broken.

**Comment by mmews-n4** [comment]
Done in commit https://github.numberfour.eu/NumberFour/n4js/commit/fd8792fb2682e220792437788b9778fcf9d9a8b7
