### ISSUE TITLE
Code formatter incorrectly formats code.

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#382]
Example issues include: 
- incorrectly removes newlines in some cases (for example within an enum)
- incorrectly indents some multiline statements (for example object literals)
- inconsistent when max line length is wrapped (some lines get wrapped some don't)
- where the line breaks is in an odd spot (for example breaks in the middle of a parameter of a long function call instead of before or after the parameter) 
- extra indentation in some cases (such as blocks in switch case statements)
- collapses braces/parens/brackets if they are spread and indented on multiple lines
- adds a single space after modeline

In general it is needed to format existing code and see if the changes match the coding guidelines.

**Comment by arrowplum** [comment]
I'm not sure if you saw this bug @qtran-n4, but you are/were looking at the code formatter, right? I haven't re-checked which of these cases worked.

**Comment by qtran-n4** [comment]
@arrowplum Thanks for the hint. I haven't had a look at this bug yet. However, there have been some improvements in the formatter both due to the newer xtext and our customization. Is this bug urgent for you?

**Comment by JensN4** [comment]
- also: single line comments are not recognized, leading to syntax error (lucky!) or semantic change (not so lucky)

**Comment by JensN4** [comment]
add Xpect tests when moving to Eclipse repo

**Comment by JensN4** [comment]
cf. https://github.com/eclipse/n4js/pull/40
