### ISSUE TITLE
Constructor suppresses file initializer of the inherited final field (override adds final)

### ISSUE THREAD

**Issue by yoosiba** [NumberFour/n4js#383]
Consider following code:
```typescript
interface I{
	public value :string;
}

class C implements I{
	@Final
	@Override
	public value = "concrete value";
	
	constructor(val :string){
		//XPECT FIXME error --> "Final field value has an initializer and may therefore not be initialized in the constructor." at "value";
		this.value = val;
	}
}

let c = new C("user value");
console.log(c.value) // error, c.value === "user value"
```

Even though filed is marked as `@Final` it is possible to initialize it in the constructor and override local field initializer. Looks like issue with inheritance, without inheritance:
```typescript
class C2 {
	@Final
	public value = "concrete value";
	
	constructor(val :string){
		//XPECT error --> "Final Field 'value' has initializer" at "value";
		this.value = val;
	}
}
```

Note, that in case with inheritance, in the body of the constructor filed is bound to the declaration in the super type (one without `@Final`) which suggests that validation is considering that type only, even though it is invoked in the sub type.

//edit
Note that the same issue happens for the spec constructor case
```typescript
class CS implements I{
	@Final
	@Override
	public value = "concrete value";
	
	constructor(@Spec spec : ~i~this){
	}
}

let cs = new CS({value:"user value"});
console.log(cs.value) // error, c.value === "user value"
```

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/550
