### ISSUE TITLE
Some (locally failing) tests are not executed on Jenkins

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#391]
See Jenkins result: 
http://build-master.corp.numberfour.eu:8080/view/N4JS_dev/job/N4JS_Marcus_1/11/org.eclipse.n4js$org.eclipse.n4js.lang.tests/testReport/org.eclipse.n4js.npmexporter/

**Bundle:** org.eclipse.n4js.lang.tests
**File:** org.eclipse.n4js.npmexporter.VersionConversionFromManifestDataTests
- parseErrors
- parseErrors2
- parseErrorsWithMeta

PS: Maybe searching for 'Tests' in all file names of test bundles would be a good idea.

**Comment by yoosiba** [comment]
fixed in https://github.com/eclipse/n4js/
