### ISSUE TITLE
Find references does not find references to enums in different modules

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#392]
File C.n4js
```
export public enum ColorEnum { 
	// XPECT FIXME findReferences --> D - 2
	RED,
	// XPECT findReferences --> C - 7
	YELLOW
}
var b = ColorEnum.YELLOW;
```

File D.n4js
```
import {ColorEnum} from "C";
var y = ColorEnum.RED;
```

In general it seems as if we have only `XPECT FIXME findReferences` in our tests and no working tests with `XPECT findReferences`.

This bug has become part of Eclipse N4JS user story: https://github.com/eclipse/n4js/issues/73

**Comment by JensN4** [comment]
@qtran-n4 Did you already create a copy of this bug in eclipse/n4js? Please do and refer to that from here.

**Comment by qtran-n4** [comment]
@JensN4 Yes I created a user story for that. The reference to that user story has been added to the description.
