### ISSUE TITLE
#72: Type inference confused (weird error, maybe proxy problem?)

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#397]
__Moved:__ https://github.com/eclipse/n4js/issues/72

The follow code issues an error:
```
export public class C {
	b: B;
	// at least correctly shown in outline view XPECT typeof d --> D
	d = new D();

	g() {
		// XPECT FIXME noerrors --> "any is not a subtype of B."
		this.b = this.d;
	}
}

abstract class B {}

class D extends B {
	protected c: C;

	f() {
		this.c.g(); // removing this line solves the error
	}
}
```

That is, although field d of C is correctly inferred as D, the assignment causes an error. However, this only happens if method C.g() is called in D.f(), which should be completely independent.

The error is also removed when C.d is explicitly typed (e.g. `d: D = new D()`).

No error in error console shown.

N4JS IDE
Build time: 2017-05-03 12:04:43

**Comment by mmews-n4** [comment]
Also, the error can be removed by moving class ```D``` to the top.
```
class D extends B {
	protected c: C;
	f() {
		this.c.g(); // removing this line solves the error
	}
}
class C {
	b: B;
	// at least correctly shown in outline view XPECT typeof d --> D
	d  = new D();
	g() {
		// XPECT FIXME noerrors --> "any is not a subtype of B."
		this.b = this.d; // no error here
	}
}
abstract class B {}
```
