### ISSUE TITLE
#71: Cycles between classes (and const/static variables) not handled correctly at runtime

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#398]
__Moved:__ https://github.com/eclipse/n4js/issues/71

```
// XPECT FIXME output --> true

class A {
	const x = new B();
}

class B extends A {}

console.log(A.x instanceof B);
```

This does not work using system.js. We either need to fix runtime or create compilation error.
This only is a problem if A and B are located in the same module. Splitting up both classes into separate modules (with export and import) solves the problem.

**Comment by JensN4** [comment]
Marked this as prio-high, as this only reveals at runtime and it is extremely hard to find.

**Comment by mmews-n4** [comment]
Note that the above can also be solved by moving the declaration of ```B``` up.
```
class B extends A {}
class A {
	const x : B = new B();
}
console.log(A.x instanceof A);  // prints: false
console.log(A.x instanceof B);  // prints: true
```

**Comment by mmews-n4** [comment]
The underlying issue is, that we have to decide whether classes shall behave statically like in Java or dynamically like in EcmaScript (see discussion issue).

**Comment by yoosiba** [comment]
This is another instance (e.g. see #28 ) of  IDE-1023  i.e. class can not be used in module before it is declared in that module.

In the IDE-1023 we touch briefly on ES6 semantics and system.js
