### ISSUE TITLE
Review relation of type and member visibility, also considering inheritance

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#40]
Since this issue is becoming a bit more complex, I'm breaking it down into tasks.
- [x] create an [access control matrix](https://docs.google.com/a/numberfour.eu/spreadsheets/d/1u8c61A3bqqApD6pd8u8XRAdMbTvEUFOtJLkCgtn0JbE/edit?usp=sharing) to manage test scenarios and expectations
- [x] build a simple code generator that can be used to generate test cases for access control validations
- [x] investigate how best to run such tests (for now, we use the headless compiler)
- [x] extend the headless compiler so that it's possible to obtain all issues from it when its called from code and executed as a separate process
- [x] create a simple builder-like syntax to match expectations against validation issues
- [x] generate the actual test scenarios from the access control matrix
- [x] add fixme as an expectation type for tests that are expected to fail under the current implementation
- [ ] specify the expected errors more precisely (location and error message)
- [ ] implement the "Same Type" scenario
- [x] factor out the test scenario creation from the actual test case to reduce the size of the class
- [ ] generate and test constructors as an additional member type (discuss with @mor-n4)
- [ ] fix all discovered bugs
- [ ] review and revise spec esp. regarding the use of the words "visible" and "accessible"
- [ ] also review the code, particularly the validations, regarding the use of these words in the code and in comments
- [ ] for spec update: make sure to add last comment of following task to spec (ask Oliver for details)!!  https://jira.numberfour.eu/browse/IDE-1553

IDEBUG-476
Having two Projects with _different vendor-ids_  there are a number of oddities w.r.t. visibiliy of members, visibility of types and inheritance.

Project with Vendor1:

```
// file Main.n4js

import { PublicInterface } from "Other"
import { Cls } from "Other";


class UseInternalSameVendor implements PublicInterface {

    // ok (unproblematic)
    @Override public methodPublic(){}

    // ok (unproblematic)
    @Override public methodDefault(){}

    // strange:
    // we are allowed to override a method that is not visible to us!
    // (we would even be allowed to increase its visibility to public)
    @Override  project methodProject(){}
    // @Override  public methodProject(){} // also no error

    // strange:
    // as above (override method not visible to use, due to different vendor)
    @Override @Internal public methodInternalPublic(){}
}



class ClsSub extends Cls {

    foo() {
        // PROBLEM: we are allowed to access 'm' but it should not be visible
        // (@Internal public with different vendor)
        // -> this is not according to spec (see Table 3.2 "Member Access Control")
        this.m();
    }
}
```

Project with Vendor2:

```
// Other.n4js

export public interface PublicInterface {

    public methodPublic();

    /*default*/ methodDefault(); // gets visibility of interface, i.e. public

    project methodProject();

    @Internal public methodInternalPublic();

    // the following error is according to spec, but since
    // "private" visibility means module-wide visibility, this seems
    // inconsistent and it might make sense to allow private members
    // (e.g. class in same module implements the interface; compare with project visibility)
    //private methodPrivate(); // error: "Members of interfaces must not be declared private."
}


export public class Cls {

    @Internal public m() {}
}
```

NOTE: current implementation: public@internal methods are in general visible in subtypes (this violates the spec!!)

Probably a general review of member visibility should be done (above code just provides some examples, there is probably more).

**Comment by kduske-n4** [comment]
See also #64

**Comment by kduske-n4** [comment]
Some additional todos before closing this task:

- [ ] review and revise spec esp. regarding the use of the words "visible" and "accessible"
- [ ] also review the code, particularly the validations, regarding the use of these words in the code and in comments
