### ISSUE TITLE
Asciidoc Export Wizard contains 'string index out of range' error

### ISSUE THREAD

**Issue by bsmith-n4** [NumberFour/n4js#400]
When exporting a project containing mixed languages, I get the following console reporting:

```
10:40:21	 Parsing code base ...
10:40:27	 String index out of range: -1
10:40:27	 Reading existing documentation ...
10:40:27	 Computing updates ...
```

This happens when I specifically export a folder containing only N4JS-related code (`.n4js`,`.n4jsd`,`.n4jsx` files).

**Comment by mmews-n4** [comment]
This should be fixed with https://github.numberfour.eu/NumberFour/n4js/pull/437
