### ISSUE TITLE
#70: n4jsc ignores resources specified in manifest

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#402]
__Moved:__ https://github.com/eclipse/n4js/issues/70

The manifest allows for specifying resources, that is, folders with arbitrary resources.
When running a project from the N4JSIDE, these resource folders are added to the NODE_PATH path. The n4jsc does not do that.

In general, it is not clear what "resources" specified in the manifest are. What happens in the case of running with a browser?

For an example, see
https://github.com/jpilgrim/spex/blob/master/spex.tests/manifest.n4mf (and the workaround in https://github.com/jpilgrim/spex/blob/master/spex.tests/src/ResourceBasedTest.n4js#L51 )

**Comment by yoosiba** [comment]
First implementation of the browser runner was based on the idea, that runner starts web server and then starts browser pointing to that server. Resources were added to the 'classpath` of the web server. Web server was serving  them and browser could load them. 

Unfortunately support for browser runner was rejected at that time (i.e. adding necessary support in bootstrap code etc.).
Implementation was not merged to master and runner itself was suppressed in the product  (i.e. user cannot invoke browser runner).
