### ISSUE TITLE
Add "launch/test with node and debug with Chrome/DevTools"

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#403]
In general it is super-easy to start a test or an app in debug mode on node and attach Chrome to it.
We should think about adding that to the runner menu.

What is required to debug?
Node.js arguments: --inspect --debug-brk
Chrome: Open chrome with "about:inspect" (will delegate to "chrome://inspect").

**Comment by yoosiba** [comment]
commented in https://github.com/NumberFour/n4js/issues/402#issuecomment-306751724

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/548
