### ISSUE TITLE
jsdoc2spec generates wrong line ranges in the index.idx file

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#405]
In the checked-in example, the line range numbers are incorrect (e.g. 22 and 23, or 24 and 41).
(Example location: `n4js/tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1`)

**Generated file index.idx**
```
n4js#tests.org.eclipse.n4js.jsdoc2spec.tests.testresourcesADoc
	SpecSample1#src
		NO_PACKAGE
			A.n4jsd
				A::15::22::23
				A#bar::20::24::41
				A#baz::27::42::61
				B::30::65::66
				B#foo::31::67::82
```

**Comment by JensN4** [comment]
Seems? Can you make that more concrete?

**Comment by mmews-n4** [comment]
fixed
