### ISSUE TITLE
getting build failure emails from robot@numberfour.eu

### ISSUE THREAD

**Issue by michaelficarra** [NumberFour/n4js#416]
I have now received 4 emails from something that appears to be associated with this project:

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-100/17/ succeeded - n4js-inhouse-multibranch/GH-100 (#17).

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-73/19/ is failing - n4js-inhouse-multibranch/GH-73 (#19). The following exception was caught : hudson.AbortException: script returned exit code 1

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-66-b/8/ is failing - n4js-inhouse-multibranch/GH-66-b (#8). The following exception was caught : hudson.AbortException: script returned exit code 1

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-73/20/ is failing - n4js-inhouse-multibranch/GH-73 (#20). The following exception was caught : hudson.AbortException: script returned exit code 1

Please stop emailing me.

**Comment by michaelficarra** [comment]
Another:

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-73/21/ is failing - n4js-inhouse-multibranch/GH-73 (#21). The following exception was caught : hudson.AbortException: script returned exit code 1

**Comment by torstenkraemer** [comment]
Hi @michaelficarra I beg you for forgiveness!
Somehow our inhouse Jenkins is picking up your mail for whatever reason. I'm working on it.

**Comment by yoosiba** [comment]
@torstenkraemer 
As a quick-fix I have disabled email notification in our main builds. At least until we figure out why [Email-ext plugin](https://wiki.jenkins.io/display/JENKINS/Email-ext+plugin) is calculating so wide recipients list.

@michaelficarra You should stop getting those emails, but it might take a moment or two for all configurations to align. Especially on developer builds, where others need to take action (adjust their feature branches / developer jobs).

**Comment by michaelficarra** [comment]
Some more:

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-73/22/ is failing - n4js-inhouse-multibranch/GH-73 (#22). The following exception was caught : hudson.AbortException: script returned exit code 1

> http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-multibranch/job/GH-66-b/9/ is failing - n4js-inhouse-multibranch/GH-66-b (#9). The following exception was caught : hudson.AbortException: script returned exit code 1

> http://build-master.corp.numberfour.eu:8080/job/CD/job/BR-3108_emailExt_bug/job/master/16/ succeeded - CD/BR-3108_emailExt_bug/master (#16).

Hopefully the branch name of that last job (30 minutes ago) means they'll be stopping soon.

I'm curious to know how my email address got wrapped up in this, considering I've had no interaction with this project before this started.

**Comment by torstenkraemer** [comment]
We added a filter to the mail-account we use to send messages. This solves the sending out of email outside of the our company. 
Sorry for any inconveniences,
Torsten

**Comment by michaelficarra** [comment]
@torstenkraemer Unfortunately, I've received another one of these emails today.

Subject:

> Jenkins build is back to stable : n4js-inhouse-smoke &#35;48

Body:

> See &lt;http://build-master.corp.numberfour.eu:8080/job/n4js-inhouse-smoke/48/display/redirect?page=changes&gt;

**Comment by torstenkraemer** [comment]
@michaelficarra  I'm totally sorry for this to happen again. We will work on that asap. Torsten.

**Comment by torstenkraemer** [comment]
@michaelficarra Fixed.
