### ISSUE TITLE
Too many manual steps when upgrading ide

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#418]
The process to upgrade the IDE (which we generally do daily)

1. Update
2.  Run all N4JS external libraries/maintenance actions (triggers rebuild even if build turned off) and find errors
3.  Run second and third maintenance actions again (another rebuild)
4.  Re import express library via quick fix in manifest file (another rebuild)
5. build clean.

This should be limited to:

1. Update (with one build clean)

**Comment by arrowplum** [comment]
despite rumors to the contrary, the situation is still the same.

**Comment by yoosiba** [comment]
see linked ticket
