### ISSUE TITLE
builtin Number.prototype.toLocaleString(locales:string|[string]=, options:Object=) missing

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#419]
Currently just inherits the Object.toLocaleString which does not accept parameters.

see linked specifications

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by arrowplum** [comment]
plsease fast track this fix since it is straightforward and causes a cast to Function

**Comment by JensN4** [comment]
I will transfer this issue to eclipse/n4js.

DO NOT ADD ANY MORE ISSUES TO THIS REPOSITORY!
