### ISSUE TITLE
Type is not properly inferred for N4JS hover provider in case of arrow expressions

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#42]
IDEBUG-482

```
class A {
    static <T> T foo({function(number): T} f) {
        return null;
    }
}

var string s = A.foo((n) => { return n.toString(); });
```

The type for `n` is inferred as `any` instead of `number` in case of the below expression.
var string s = A.foo((`n`) => { return `n`.toString(); });

Could be only UI related issue but the UI is getting this information from {{RuleEnvironment}}.

**Comment by mor-n4** [comment]
this is now working properly (verified on July 5, 2016)
(the bug was created before the type system refactoring from summer 2015 was merged to master, so this was probably solved by the TS refactoring)
