### ISSUE TITLE
Type variable substitution gets messed up in corner cases (multiple implementation of an interface)

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#43]
IDEBUG-487
 In the below example, the subtition of the type variable T in the return type of the get-iterator method gets confused by the many direct and indirect implementations of Iterable (the inferred type of the return value still contains some type variables!):

```
class A {}
class B {}
class C {}
class D {}
class E {}
class F {}
class G {}

interface Intermediate<I1,I2> extends Iterable2<I1,I2> {}
abstract class X8 implements Iterable2<C,D> {}
abstract class Y8 extends X8 implements Intermediate<A,B> {}
abstract class Z8 extends Y8 implements Iterable3<E,F,G> {}


var Z8 z8;
var string test = z8[Symbol.iterator]();
// error: "Iterator<union{intersection{A,C,E},intersection{union{T2,T3},B,D}}> is not a subtype of string."
```

NOTE: it is not 100% clear if we even want to allow inheritance hierarchies as above, so maybe this should be clarified before spending great effort on fixing this bug.

If Ref is defined as follows

```
interface Ref<T> { 
    get t(): T {return null};
}
```

the sample should work (of course with the assignment).

Same case as for the field for setter:

```
interface Ref<T> { 
    set t(t: T) {};
}

class XRef implements Ref<X> {}
// XPECT FIXME errors --> "Type of setter YRef.t does not conform to overridden setter XRef.t: X is not a subtype of Y."
// or 
// XPECT FIXME errors --> "The interface Ref cannot be implemented more than once with different arguments: Ref<X> and Ref<Y>"
class YRef extends XRef implements Ref<Y> {}
```

Overall, override constraints must be applied in case of redundant interface implementations.

One additional note regarding default implementations:
It should even be possible to provide a default implementation for the getter:

```
interface Ref<T> { 
    protected _t: any;
    get t(): T { return this._t as T};
}
```

Of course, implementors have to deal with that as well.

A different example:

```
class X {}
class Y extends X{ foo(){} }

interface Ref<T> { t: T; }

class XRef implements Ref<X> {}
// XPECT FIXME errors --> "Type of field YRef.t must equal type of overridden field XRef.t."
// or 
// XPECT FIXME errors --> "The interface Ref cannot be implemented more than once with different arguments: Ref<X> and Ref<Y>"

class YRef extends XRef implements Ref<Y> {}

var xref: XRef;
var yref: YRef = new YRef();

xref = yref;
xref.t = new X();

var y0 = yref.t; // type of y0: intersection{X,Y}
var y: Y = yref.t; // weird!

y.foo(); // argh!
```

Java does not allow redundant implementation of interfaces, i.e. Java would issue the following error at YRef: The interface Ref cannot be implemented more than once with different arguments: Ref<X> and Ref<Y>

With proper substitution it should be possible to allow that. In YRef, t is substituted as intersection{X,Y}. At the moment, we do not check the elements of an intersection. The question is, whether 
    Y <: intersection{X,Y}
is true, or, in other words, if intersection{X,Y} can be reduced to Y is Y <: X if true.

**Comment by mor-n4** [comment]
see #55

**Comment by mor-n4** [comment]
added validation to disallow multiple implementation of interfaces unless type arguments are equal (cf. IDE-2235); for a follow-up task about definition-site variance see IDE-2226.
