### ISSUE TITLE
@Ignore is ignored by test execution inside IDE

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#45]
IDEBUG-499
 If a test is annotated with @Ignore, it must not be executed when run inside the IDE via "Run as / Test in Node.js". At the moment, the @Ignore annotation is ignored.

Also see N4IDESpec, 9.1.2.7 Test Ignore

**Comment by JensN4** [comment]
cf. IDE-1512

**Comment by torstenkraemer** [comment]
Documentation is a little bit sloppy, please improve "Test Skip" should be "Test Ignore", "proffered" --> "preferred"
