### ISSUE TITLE
Disallow extending built-in types

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#5]
IDEBUG-60
 Disallow extending built-in types except Object and Error.

```
class A extends Function {
}

var Function a = new A("arg1", "arg2", "return arg1 + arg2")
var args = new Array<String>(2)
args.push(new String("a"), new String("b"))
a.apply(this, args)
console.log(a.length)
```

will throw Function.prototype.toString is not generic

see also this article that points out that sub classing of Arrays is forbidden in EcmaScript5: http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/

**Comment by yoosiba** [comment]
see https://github.com/eclipse/n4js/issues/105
