### ISSUE TITLE
Problem with void and type constraints

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#68]
IDEBUG-668

```
class A<T> {}
class B<T> extends A<T> {}

function <T_A extends A<?>> fn(T_A a) {}

// XPECT noerrors --> "B<void> is not a subtype of T_A."
fn(new B<void>)
```

Remark: This is not really a bug; the problem is that the use of void as a type argument is an open issue.
There exists a task for this: IDE-1579

**Comment by JensN4** [comment]
Talk with stdlib team about consequences -- they have several IDEBUG annotations to work around that issue.

**Comment by mor-n4** [comment]
as of IDE-1579, `void` is disallowed as type argument and `undefined` is to be used instead.

The code from the task description now works with the following minor adjustments:

```
class A<T> {}
class B<T> extends A<T> {}

function <T_A extends A<?>> fn(a: T_A) {}

// XPECT noerrors -->
fn(new B<undefined>)
```

Closing this task as fixed.
