### ISSUE TITLE
N4Classifier.members() method does not filter static fields when supposed to.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#71]
IDEBUG-675

```
class B {
    static s = 10;
}

console.log((N4Type.of(new B()) as N4Classifier).members(true, true, false))
```

The 3rd argument to members() is explicitly false, to filter out the static fields.

Output : 

```
[ { origin: undefined, annotations: [], name: 's', isStatic: true } ]
```

Expected an empty array to be returned. Instead it returns the static field.

**Comment by arrowplum** [comment]
I think this is still not working or am I missunderstanding?

```javascript
export public class A {
    protected static foo;
    public static blast;
    printem() {
        for (const field of this.constructor.n4type.dataFields(true, true, false)) {
            console.log(field.name);
        }
    }
}
new A().printem();
//foo
//blast
```

**Comment by arrowplum** [comment]
I think this issue should be reopened.

**Comment by mor-n4** [comment]
for me, your snippet prints out nothing, which seems to be the desired behavior, as you pass in `false` for the last parameter of `#dataFields()`. When I change the last argument to `true`, then it prints out
```
foo
blast
```
So this seems to work as intended. What am I missing?

**Comment by arrowplum** [comment]
no for me it returns foo blast. that is what I am saying, i get it even though I send in false.
