### ISSUE TITLE
Rethink issues that are created for problematic imports

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#77]
IDEBUG-702
 After full ES6 syntax is available (IDE-1580) and implementation of import features is included (IDE-1744) revisit issue markers generated for import related elements. In particular:
- ambiguous import: is it needed, when it is visible to user
- does it make sense to put multiple issues on the element, if not, what is hierarchy of issues
- unused import issue, and its relation to ambiguous imports and other errors

Note: related logic is in {{N4JSImportValidator}} and {{ImportedElementsScopingHelper}}

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/602
