### ISSUE TITLE
It is not possible to use Array.apply

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#78]
IDEBUG-704
 In JS it is possible to use {{Array.apply}} to create array instance.
In N4JS this causes validation error complaining about unresolved ref to {{apply}}

{panel:title=Bug report|borderStyle=dashed|borderColor=#ccc|titleBGColor=#8192A6|bgColor=#dedee0}
{{ArrayApply.n4js.xt}}

```
/* XPECT output ---
<==
stdout:
[ 1, 2, 3 ]
stderr:
==>
--- */

//XPECT FIXME noerrors ---> "Couldn't resolve reference to IdentifiableElement 'apply'." at "apply"
var a = Array.apply(undefined, [1, 2, 3]);
console.log(a)
```

{panel}

**Comment by mor-n4** [comment]
fixed by #219 / #221
