### ISSUE TITLE
It is not possible to use Function.apply

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#79]
IDEBUG-705
 In JS it is possible to use {{Function.apply}} to create function instance.
In N4JS this causes validation error complaining about static access to non static property {{apply}}

{panel:title=Bug report|borderStyle=dashed|borderColor=#ccc|titleBGColor=#8192A6|bgColor=#dedee0}
{{ArrayApply.n4js.xt}}

```
/* XPECT output ---
<==
stdout:
function anonymous(par1,par2
/\**\/) {
par3
}
stderr:
==>
--- */

function print(par){
    console.log(print.toString.call(par))
}


//XPECT FIXME noerrors ---> "The non-static member apply cannot be accessed from a static context." at "apply"
var f = Function.apply(undefined, ['par1', 'par2', 'par3'])
print(f)
```

{panel}

**Comment by mor-n4** [comment]
fixed by #219 / #221
