### ISSUE TITLE
Handle module name when same module name is defined in several project dependencies

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#8]
IDEBUG-160
 Scenario:
- Project1 with src/a/A.n4js and export public class A{}
- Project2 with src/a/A.n4js and export public class A{}
- Project3 
  *\* with project dependencies to Project1 and Project2
  *\* with src/a/A.n4js and export public class A{}
  *\* src/a/B.n4js and 

```
import A from "A"
class B extends A {
}
```

Question is, to which module does "A" link?
1. to a.A.A in Project1?
2. to a.A.A in Project2?
3. to a.A.A in Project3?

Possible solutions: Export module to Xtext index with its Complete Module Specifier (e.g. project$-$1.0.0/p/C) (clf. N4JS Spec) and raise a validation issue if there is a clash. On the other hand there is currently no way to resolve such a conflict (other than renaming the module in one of the depending projects).

background: This issue was discovered while migrating AT_084_Test.test_15 (now removed, as this test didn't respect manifest configuration) in context of IDE-1075.

Solution: Adding the project name to module specifier. We have to update spec and implementation accordingly.
If there is a conflict detected, issues should be raised.
This is already done:
- document new feature
- add test
- close this issue

**Comment by mor-n4** [comment]
Most of this is fixed by now, but one part of the problem remains and was moved to `https://github.com/eclipse/n4js/issues/556`.
