### ISSUE TITLE
Missing validation for computed names

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#80]
IDEBUG-706
 This is a minor thing, but if the computed property name is not a string, an error should be raised.

```
class C {
    // XPECT errors --> "computed names should be a string value."
    [foo.bar];
}
```

The grammar should accept in the position above only Symbol.iterator and not any arbitrary IDENTIFIER.IDENTIFIER

**Comment by mor-n4** [comment]
This is actually a bug in the grammar; a proper validation exists, but it gets a wrong AST and therefore does not recognize the above case.

This is also the cause for #118.
