### ISSUE TITLE
N4Type.of does not throw exception if argument is not an N4Object

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#81]
IDEBUG-708
 {{N4Type.of("hey this doesn't work")}} returns {{undefined}} but it should throw an IllegalArgument error.

**Comment by mor-n4** [comment]
see also #18

**Comment by mor-n4** [comment]
after discussion with Daniel and following the conclusion of the discussion in the comments of IDEBUG-258, N4Type.of was _not_ changed to throw an error but instead it still returns `undefined` if given an invalid value. However, some other refinements were made (now accepts values of type `type{C}`).
