### ISSUE TITLE
Clean up StructuralTypesHelper API wrt getting iterator of structural members

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#86]
IDEBUG-723
 Eliminate boolean hack from argument list of {{eu.numberfour.ide.n4js.utils.StructuralTypesHelper.getMembersTripleIterator(RuleEnvironment, TypeRef, TypeRef, boolean)}} method.

Remove {{restrictInitTyping}} argument. Currently the getters are returned from the member filter if a type has a getter/setter accessor pair. The getter is the proper one when creating the type constraints. But when having {{~i~}} type, setters should return if both getter and setters are available, which breaks the type checking. For instance union{string,int} is returned when string should be returned. See: {{Constraints_55_9_Structural_Fields_Can_Be_Assigned_Via_Public_Accessors.n4js.xt}} for more details.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/600
