### ISSUE TITLE
Incorrect transpilation of async functions

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#93]
IDEBUG-770
 Transpiling async function produces incorrect output specifically extra `yield undefined;`. See example:

``` js
//input
async function foo(arg) {
    await Promise.resolve(1);
}
//output
    var foo = function foo(arg) {
        return $spawn(function*() {
            (yield Promise.resolve(1));
            (yield undefined);
            return;
        }.bind(this));
    };
//should be
    var foo = function foo(arg) {
        return $spawn(function*() {
            (yield Promise.resolve(1));
            (return undefined);
        }.bind(this));
    };
```

After changes ensure that at runtime it works correctly with `$spawn` function.

_Proposal_ from @dbo see stdlib branch IDEBUG-770:
IMHO we should also fix correct arguments support, i.e. the inner generator currently has no access on the correct arguments object (w.r.t. arguments and `callee.name`). I think the correct _transpiled_ output should be this:

``` js
    var foo = function() {
        return $spawn(function* foo(arg) {
            (yield Promise.resolve(1));
        }.apply(this, arguments));
    };
```

Work with @dbo to ensure proper async behaviour and proper update of _all_ copies of runtime bootstrap.

Worth to read the original spec of TC39: https://tc39.github.io/ecmascript-asyncawait/
It has a de-sugared impl art the end: https://tc39.github.io/ecmascript-asyncawait/#desugaring

**Comment by mor-n4** [comment]
note that for the problem with the "arguments" variable, there is a separate issue #89 
but I agree with Daniel that it's probably a good idea to fix those two issues together

**Comment by dbo** [comment]
I just saw that the arguments are not part of inner generator function, but still part of the outer one.
