### ISSUE TITLE
Invalid error for arguments parameter in arrow expressions

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#96]
IDEBUG-789
 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_arguments

> Arrow functions do not expose an arguments object to their code

```
var a = [1,2,3];
// XPECT FIXME noerrors --> Parameter arguments shadows implicit function parameter.
a.map(arguments => arguments.toString())
```

Currently code above has error `Parameter arguments shadows implicit function parameter.`
There must be no error at all.

**Comment by mor-n4** [comment]
the error shown by N4JS is correct; run the code from the task description in node.js (**with strict mode turned on!**) and you will get the following runtime exception:

```
a.map(arguments => arguments.toString())
      ^^^^^^^^^
SyntaxError: Unexpected eval or arguments in strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

Only the error message is a bit misleading.

**Comment by mor-n4** [comment]
see constraint on BindingIdentifier in Annex C in ES6 spec:
http://www.ecma-international.org/ecma-262/6.0/index.html#sec-strict-mode-of-ecmascript
