### ISSUE TITLE
Consider disallowing StaticPolyfill for n4jsd files.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#97]
IDEBUG-792
 Static poly-filling is only allowed within the same project. Nevertheless, you can create n4jsd-files and make them {{@StaticPolyfillAware}} & {{@StaticPolyfillModule}}

It is not really clear, if this is desired and if there is any reasonable use-case ( maybe together with api-impl & generators ? ). 

Investigate possible scenarios and document / adapt if some are found, otherwise disallow & update spec.

**Comment by mor-n4** [comment]
probably just add validation to disallow for now and we will reconsider it when we need it
BUT: first discuss with Torsten & Daniel

**Comment by mor-n4** [comment]
as it turned out, there is a use case for static polyfills in `.n4jsd` files (in API projects)

will update spec & add a test for this case
